// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double aces_channel(double x) {
    double a;
    double b;
    double c;
    double d;
    double e;
    double _7;
    double _8;
    double _9;
    double num;
    double _11;
    double _12;
    double _13;
    double _14;
    double den;
    double _16;
    a = 2.51;
    b = 0.03;
    c = 2.43;
    d = 0.59;
    e = 0.14;
    _7 = (a * x);
    _8 = (_7 + b);
    _9 = (x * _8);
    num = _9;
    _11 = (c * x);
    _12 = (_11 + d);
    _13 = (x * _12);
    _14 = (_13 + e);
    den = _14;
    _16 = (num / den);
    return _16;
}

vec4 fs_tonemap(vec3 hdr_color) {
    double _2;
    double _3;
    double r;
    double _5;
    double _6;
    double g;
    double _8;
    double _9;
    double b;
    vec4 _11;
    _2 = hdr_color.x;
    _3 = aces_channel(_2);
    r = _3;
    _5 = hdr_color.y;
    _6 = aces_channel(_5);
    g = _6;
    _8 = hdr_color.z;
    _9 = aces_channel(_8);
    b = _9;
    _11 = vec4(r, g, b, 1.0);
    return _11;
}

