// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double select_bright(double x) {
    bool _2;
    double _3;
    _2 = (x > 0.5);
    if (_2) {
        _3 = 1.0;
        return _3;
    } else {
        _3 = 0.0;
    }
    return _3;
}

vec4 fs_main(vec3 color) {
    double _2;
    double _3;
    double r;
    double _5;
    double _6;
    double g;
    double _8;
    double _9;
    double b;
    vec4 _11;
    _2 = color.x;
    _3 = select_bright(_2);
    r = _3;
    _5 = color.y;
    _6 = select_bright(_5);
    g = _6;
    _8 = color.z;
    _9 = select_bright(_8);
    b = _9;
    _11 = vec4(r, g, b, 1.0);
    return _11;
}

