// Generated by QuantaLang Compiler
// Do not edit manually

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


// ============================================================================
// QuantaLang Runtime Library
// Embedded in generated C output - do not edit
// ============================================================================

// --- String type ---

typedef struct {
    const char* ptr;
    size_t len;
    size_t cap;    // 0 for string literals (not heap-allocated)
} QuantaString;

static QuantaString quanta_string_new(const char* s) {
    QuantaString qs;
    qs.ptr = s;
    qs.len = strlen(s);
    qs.cap = 0; // literal, not owned
    return qs;
}

static QuantaString quanta_string_concat(QuantaString a, QuantaString b) {
    size_t new_len = a.len + b.len;
    char* buf = (char*)malloc(new_len + 1);
    memcpy(buf, a.ptr, a.len);
    memcpy(buf + a.len, b.ptr, b.len);
    buf[new_len] = '\0';
    QuantaString qs;
    qs.ptr = buf;
    qs.len = new_len;
    qs.cap = new_len + 1;
    return qs;
}

static size_t quanta_string_len(QuantaString s) {
    return s.len;
}

static bool quanta_string_eq(QuantaString a, QuantaString b) {
    if (a.len != b.len) return false;
    return memcmp(a.ptr, b.ptr, a.len) == 0;
}

static void quanta_string_free(QuantaString s) {
    if (s.cap > 0) free((void*)s.ptr);
}

// --- Vec (dynamic array) type ---

typedef struct {
    void* ptr;
    size_t len;
    size_t cap;
    size_t elem_size;
} QuantaVec;

static QuantaVec quanta_vec_new(size_t elem_size) {
    QuantaVec v;
    v.ptr = NULL;
    v.len = 0;
    v.cap = 0;
    v.elem_size = elem_size;
    return v;
}

static void quanta_vec_push(QuantaVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->ptr = realloc(v->ptr, v->cap * v->elem_size);
    }
    memcpy((char*)v->ptr + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* quanta_vec_get(QuantaVec* v, size_t index) {
    return (char*)v->ptr + index * v->elem_size;
}

static void quanta_vec_free(QuantaVec* v) {
    free(v->ptr);
    v->ptr = NULL;
    v->len = 0;
    v->cap = 0;
}

// --- Print formatting helpers ---

static void quanta_print_i32(int32_t v) { printf("%d", v); }
static void quanta_print_i64(int64_t v) { printf("%lld", (long long)v); }
static void quanta_print_f32(float v) { printf("%g", (double)v); }
static void quanta_print_f64(double v) { printf("%g", v); }
static void quanta_print_bool(bool v) { printf("%s", v ? "true" : "false"); }
static void quanta_print_str(const char* v) { printf("%s", v); }
static void quanta_print_string(QuantaString v) { printf("%.*s", (int)v.len, v.ptr); }
static void quanta_print_char(char v) { printf("%c", v); }

// --- Math built-in helpers ---

static int32_t quanta_min_i32(int32_t a, int32_t b) { return a < b ? a : b; }
static int32_t quanta_max_i32(int32_t a, int32_t b) { return a > b ? a : b; }
static int64_t quanta_min_i64(int64_t a, int64_t b) { return a < b ? a : b; }
static int64_t quanta_max_i64(int64_t a, int64_t b) { return a > b ? a : b; }
static double quanta_min_f64(double a, double b) { return a < b ? a : b; }
static double quanta_max_f64(double a, double b) { return a > b ? a : b; }
static float quanta_min_f32(float a, float b) { return a < b ? a : b; }
static float quanta_max_f32(float a, float b) { return a > b ? a : b; }

// --- Vector Math Types ---

typedef struct { double x, y; } quanta_vec2;
typedef struct { double x, y, z; } quanta_vec3;
typedef struct { double x, y, z, w; } quanta_vec4;
typedef struct { double m[4][4]; } quanta_mat4;

// Constructors
static quanta_vec2 quanta_vec2_new(double x, double y) { return (quanta_vec2){x, y}; }
static quanta_vec3 quanta_vec3_new(double x, double y, double z) { return (quanta_vec3){x, y, z}; }
static quanta_vec4 quanta_vec4_new(double x, double y, double z, double w) { return (quanta_vec4){x, y, z, w}; }

// Vector dot product
static double quanta_dot2(quanta_vec2 a, quanta_vec2 b) { return a.x*b.x + a.y*b.y; }
static double quanta_dot3(quanta_vec3 a, quanta_vec3 b) { return a.x*b.x + a.y*b.y + a.z*b.z; }
static double quanta_dot4(quanta_vec4 a, quanta_vec4 b) { return a.x*b.x + a.y*b.y + a.z*b.z + a.w*b.w; }

// Vector length
static double quanta_length2(quanta_vec2 v) { return sqrt(quanta_dot2(v, v)); }
static double quanta_length3(quanta_vec3 v) { return sqrt(quanta_dot3(v, v)); }
static double quanta_length4(quanta_vec4 v) { return sqrt(quanta_dot4(v, v)); }

// Vector normalize
static quanta_vec2 quanta_normalize2(quanta_vec2 v) { double l = quanta_length2(v); return (quanta_vec2){v.x/l, v.y/l}; }
static quanta_vec3 quanta_normalize3(quanta_vec3 v) { double l = quanta_length3(v); return (quanta_vec3){v.x/l, v.y/l, v.z/l}; }
static quanta_vec4 quanta_normalize4(quanta_vec4 v) { double l = quanta_length4(v); return (quanta_vec4){v.x/l, v.y/l, v.z/l, v.w/l}; }

// Cross product (vec3 only)
static quanta_vec3 quanta_cross(quanta_vec3 a, quanta_vec3 b) {
    return (quanta_vec3){a.y*b.z - a.z*b.y, a.z*b.x - a.x*b.z, a.x*b.y - a.y*b.x};
}

// Reflect
static quanta_vec3 quanta_reflect3(quanta_vec3 v, quanta_vec3 n) {
    double d = quanta_dot3(v, n);
    return (quanta_vec3){v.x - 2.0*d*n.x, v.y - 2.0*d*n.y, v.z - 2.0*d*n.z};
}

// Lerp
static quanta_vec2 quanta_lerp2(quanta_vec2 a, quanta_vec2 b, double t) {
    return (quanta_vec2){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t};
}
static quanta_vec3 quanta_lerp3(quanta_vec3 a, quanta_vec3 b, double t) {
    return (quanta_vec3){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t, a.z + (b.z-a.z)*t};
}
static quanta_vec4 quanta_lerp4(quanta_vec4 a, quanta_vec4 b, double t) {
    return (quanta_vec4){a.x + (b.x-a.x)*t, a.y + (b.y-a.y)*t, a.z + (b.z-a.z)*t, a.w + (b.w-a.w)*t};
}

// Vec2 arithmetic
static quanta_vec2 quanta_vec2_add(quanta_vec2 a, quanta_vec2 b) { return (quanta_vec2){a.x+b.x, a.y+b.y}; }
static quanta_vec2 quanta_vec2_sub(quanta_vec2 a, quanta_vec2 b) { return (quanta_vec2){a.x-b.x, a.y-b.y}; }
static quanta_vec2 quanta_vec2_mul(quanta_vec2 a, quanta_vec2 b) { return (quanta_vec2){a.x*b.x, a.y*b.y}; }
static quanta_vec2 quanta_vec2_scale(quanta_vec2 v, double s) { return (quanta_vec2){v.x*s, v.y*s}; }
static quanta_vec2 quanta_vec2_neg(quanta_vec2 v) { return (quanta_vec2){-v.x, -v.y}; }

// Vec3 arithmetic
static quanta_vec3 quanta_vec3_add(quanta_vec3 a, quanta_vec3 b) { return (quanta_vec3){a.x+b.x, a.y+b.y, a.z+b.z}; }
static quanta_vec3 quanta_vec3_sub(quanta_vec3 a, quanta_vec3 b) { return (quanta_vec3){a.x-b.x, a.y-b.y, a.z-b.z}; }
static quanta_vec3 quanta_vec3_mul(quanta_vec3 a, quanta_vec3 b) { return (quanta_vec3){a.x*b.x, a.y*b.y, a.z*b.z}; }
static quanta_vec3 quanta_vec3_scale(quanta_vec3 v, double s) { return (quanta_vec3){v.x*s, v.y*s, v.z*s}; }
static quanta_vec3 quanta_vec3_neg(quanta_vec3 v) { return (quanta_vec3){-v.x, -v.y, -v.z}; }

// Vec4 arithmetic
static quanta_vec4 quanta_vec4_add(quanta_vec4 a, quanta_vec4 b) { return (quanta_vec4){a.x+b.x, a.y+b.y, a.z+b.z, a.w+b.w}; }
static quanta_vec4 quanta_vec4_sub(quanta_vec4 a, quanta_vec4 b) { return (quanta_vec4){a.x-b.x, a.y-b.y, a.z-b.z, a.w-b.w}; }
static quanta_vec4 quanta_vec4_mul(quanta_vec4 a, quanta_vec4 b) { return (quanta_vec4){a.x*b.x, a.y*b.y, a.z*b.z, a.w*b.w}; }
static quanta_vec4 quanta_vec4_scale(quanta_vec4 v, double s) { return (quanta_vec4){v.x*s, v.y*s, v.z*s, v.w*s}; }
static quanta_vec4 quanta_vec4_neg(quanta_vec4 v) { return (quanta_vec4){-v.x, -v.y, -v.z, -v.w}; }

// --- Mat4 operations ---

static quanta_mat4 quanta_mat4_identity(void) {
    quanta_mat4 m = {{{1,0,0,0},{0,1,0,0},{0,0,1,0},{0,0,0,1}}};
    return m;
}

static quanta_mat4 quanta_mat4_mul(quanta_mat4 a, quanta_mat4 b) {
    quanta_mat4 r = {{{0}}};
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            for (int k = 0; k < 4; k++)
                r.m[i][j] += a.m[i][k] * b.m[k][j];
    return r;
}

static quanta_vec4 quanta_mat4_mul_vec4(quanta_mat4 m, quanta_vec4 v) {
    return (quanta_vec4){
        m.m[0][0]*v.x + m.m[0][1]*v.y + m.m[0][2]*v.z + m.m[0][3]*v.w,
        m.m[1][0]*v.x + m.m[1][1]*v.y + m.m[1][2]*v.z + m.m[1][3]*v.w,
        m.m[2][0]*v.x + m.m[2][1]*v.y + m.m[2][2]*v.z + m.m[2][3]*v.w,
        m.m[3][0]*v.x + m.m[3][1]*v.y + m.m[3][2]*v.z + m.m[3][3]*v.w
    };
}

static quanta_mat4 quanta_mat4_translate(quanta_vec3 t) {
    quanta_mat4 m = quanta_mat4_identity();
    m.m[0][3] = t.x; m.m[1][3] = t.y; m.m[2][3] = t.z;
    return m;
}

static quanta_mat4 quanta_mat4_scale(quanta_vec3 s) {
    quanta_mat4 m = {{{s.x,0,0,0},{0,s.y,0,0},{0,0,s.z,0},{0,0,0,1}}};
    return m;
}

static quanta_mat4 quanta_mat4_perspective(double fov, double aspect, double near_val, double far_val) {
    double f = 1.0 / tan(fov * 0.5);
    quanta_mat4 m = {{{0}}};
    m.m[0][0] = f / aspect;
    m.m[1][1] = f;
    m.m[2][2] = (far_val + near_val) / (near_val - far_val);
    m.m[2][3] = (2.0 * far_val * near_val) / (near_val - far_val);
    m.m[3][2] = -1.0;
    return m;
}

// --- Shader math functions ---

static double quanta_clampf(double x, double lo, double hi) { return x < lo ? lo : (x > hi ? hi : x); }
static quanta_vec3 quanta_clamp3(quanta_vec3 v, double lo, double hi) {
    return (quanta_vec3){quanta_clampf(v.x, lo, hi), quanta_clampf(v.y, lo, hi), quanta_clampf(v.z, lo, hi)};
}
static double quanta_smoothstep(double edge0, double edge1, double x) {
    double t = quanta_clampf((x - edge0) / (edge1 - edge0), 0.0, 1.0);
    return t * t * (3.0 - 2.0 * t);
}
static double quanta_mix(double a, double b, double t) { return a + (b - a) * t; }
static double quanta_fract(double x) { return x - floor(x); }
static double quanta_step(double edge, double x) { return x < edge ? 0.0 : 1.0; }

// --- Effect handler runtime (setjmp/longjmp based) ---

#include <setjmp.h>

// Effect handler stack
typedef struct QuantaHandler {
    jmp_buf env;
    int32_t effect_id;
    void* handler_data;
    struct QuantaHandler* parent;
} QuantaHandler;

// Global handler stack
static QuantaHandler* __quanta_handler_stack = NULL;

// Push a handler onto the stack
static void quanta_push_handler(QuantaHandler* h, int32_t effect_id) {
    h->effect_id = effect_id;
    h->handler_data = NULL;
    h->parent = __quanta_handler_stack;
    __quanta_handler_stack = h;
}

// Pop a handler from the stack
static void quanta_pop_handler(void) {
    if (__quanta_handler_stack) {
        __quanta_handler_stack = __quanta_handler_stack->parent;
    }
}

// Perform an effect operation — jumps to the nearest handler
static void quanta_perform(int32_t effect_id, int32_t op_id, void* arg, void* result) {
    QuantaHandler* h = __quanta_handler_stack;
    while (h) {
        if (h->effect_id == effect_id) {
            h->handler_data = arg;
            longjmp(h->env, op_id + 1); // +1 because setjmp returns 0 on first call
        }
        h = h->parent;
    }
    // Unhandled effect — abort
    fprintf(stderr, "Unhandled effect %d operation %d\n", effect_id, op_id);
    abort();
}

// --- File I/O ---

static QuantaString quanta_read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return quanta_string_new("");
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    QuantaString qs;
    qs.ptr = buf;
    qs.len = (size_t)len;
    qs.cap = (size_t)(len + 1);
    return qs;
}

static bool quanta_write_file(const char* path, const char* content) {
    FILE* f = fopen(path, "wb");
    if (!f) return false;
    size_t len = strlen(content);
    size_t written = fwrite(content, 1, len, f);
    fclose(f);
    return written == len;
}

static bool quanta_file_exists(const char* path) {
    FILE* f = fopen(path, "rb");
    if (f) { fclose(f); return true; }
    return false;
}

// --- Process / Environment ---

static int32_t quanta_exit(int32_t code) {
    exit(code);
    return code; // unreachable
}

// --- Graphics Stub (Vulkan helper) ---
// Minimal stub that prints what a real Vulkan backend would do.
// Used for testing the FFI integration pattern.
// When connected to a real Vulkan backend, these are replaced by
// linking against vulkan_helper.c / the Vulkan SDK.

typedef struct {
    int32_t initialized;
    int32_t width;
    int32_t height;
    int32_t frame_count;
    int32_t should_close;
} QuantaGfxContext;

static QuantaGfxContext __quanta_gfx_ctx = {0, 0, 0, 0, 0};

static int32_t quanta_gfx_init(int32_t width, int32_t height, const char* title) {
    printf("[GFX] Initializing %dx%d window: %s\n", width, height, title);
    __quanta_gfx_ctx.initialized = 1;
    __quanta_gfx_ctx.width = width;
    __quanta_gfx_ctx.height = height;
    __quanta_gfx_ctx.frame_count = 0;
    __quanta_gfx_ctx.should_close = 0;
    printf("[GFX] Vulkan instance created\n");
    printf("[GFX] Physical device selected\n");
    printf("[GFX] Logical device created\n");
    printf("[GFX] Swapchain created (%dx%d)\n", width, height);
    return 1;
}

static int32_t quanta_gfx_load_shader(const char* path, int32_t stage) {
    printf("[GFX] Loading shader: %s (stage=%s)\n", path, stage == 0 ? "vertex" : "fragment");
    return 1;
}

static int32_t quanta_gfx_create_pipeline(int32_t vertex_shader, int32_t fragment_shader) {
    printf("[GFX] Creating graphics pipeline (vs=%d, fs=%d)\n", vertex_shader, fragment_shader);
    return 1;
}

static void quanta_gfx_begin_frame(void) {
    __quanta_gfx_ctx.frame_count++;
    if (__quanta_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Begin frame %d\n", __quanta_gfx_ctx.frame_count);
    }
}

static void quanta_gfx_clear(float r, float g, float b, float a) {
    if (__quanta_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Clear (%.1f, %.1f, %.1f, %.1f)\n", r, g, b, a);
    }
}

static void quanta_gfx_draw(int32_t vertex_count) {
    if (__quanta_gfx_ctx.frame_count <= 3) {
        printf("[GFX] Draw %d vertices\n", vertex_count);
    }
}

static void quanta_gfx_end_frame(void) {
    if (__quanta_gfx_ctx.frame_count <= 3) {
        printf("[GFX] End frame %d\n", __quanta_gfx_ctx.frame_count);
    }
    if (__quanta_gfx_ctx.frame_count >= 3) {
        __quanta_gfx_ctx.should_close = 1;
    }
}

static int32_t quanta_gfx_should_close(void) {
    return __quanta_gfx_ctx.should_close;
}

static void quanta_gfx_shutdown(void) {
    printf("[GFX] Shutdown complete (%d frames rendered)\n", __quanta_gfx_ctx.frame_count);
    __quanta_gfx_ctx.initialized = 0;
}

// ============================================================================
// End QuantaLang Runtime
// ============================================================================

// Type definitions
// String table
static const char* __str0 = "=== Cook-Torrance PBR BRDF — QuantaLang Dual-Target ===\n";
static const char* __str1 = "\n";
static const char* __str2 = "Fresnel (head-on, F0=0.04): %g (expect ~0.04)\n";
static const char* __str3 = "Fresnel (grazing, F0=0.04): %g (expect ~1.0)\n";
static const char* __str4 = "GGX D (n·h=1, rough=0.5): %g (expect high peak)\n";
static const char* __str5 = "GGX D (n·h=0.5, rough=0.5): %g (expect lower)\n";
static const char* __str6 = "Smith G (n·v=0.8, n·l=0.8, rough=0.5): %g\n";
static const char* __str7 = "PBR dielectric (rough=0.4): %g\n";
static const char* __str8 = "PBR metal (rough=0.3): %g\n";
static const char* __str9 = "PBR smooth (rough=0.1): %g\n";
static const char* __str10 = "PBR rough  (rough=0.9): %g\n";
static const char* __str11 = "=== Same functions compile to Vulkan 1.0 SPIR-V ===\n";

// Forward declarations
static double pi(void);
static double fresnel_schlick(double cos_theta, double f0);
static double distribution_ggx(double n_dot_h, double roughness);
static double geometry_schlick_ggx(double n_dot_v, double roughness);
static double geometry_smith(double n_dot_v, double n_dot_l, double roughness);
static double cook_torrance_specular(double n_dot_h, double n_dot_v, double n_dot_l, double h_dot_v, double roughness, double f0);
static double pbr_lighting(double n_dot_h, double n_dot_v, double n_dot_l, double h_dot_v, double albedo, double roughness, double metallic);
static double aces_tonemap(double x);
static double linear_to_srgb(double x);
static quanta_vec4 fs_pbr(quanta_vec3 inputs);
int32_t main(void);

static double pi(void) {
    double _ret;

    return 3.14159265358979;
}

static double fresnel_schlick(double cos_theta, double f0) {
    double _ret;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;

    _3 = (1 - f0);
    _4 = (1 - cos_theta);
    _5 = quanta_clampf(_4, 0, 1);
    goto bb1;
bb1:
    _6 = pow(_5, 5);
    goto bb2;
bb2:
    _7 = (_3 * _6);
    _8 = (f0 + _7);
    return _8;
}

static double distribution_ggx(double n_dot_h, double roughness) {
    double _ret;
    double _3;
    double a;
    double _5;
    double a2;
    double _7;
    double _8;
    double _9;
    double _10;
    double denom_term;
    double _12;
    double _13;
    double _14;
    double denom;
    double _16;

    _3 = (roughness * roughness);
    a = _3;
    _5 = (a * a);
    a2 = _5;
    _7 = (n_dot_h * n_dot_h);
    _8 = (a2 - 1);
    _9 = (_7 * _8);
    _10 = (_9 + 1);
    denom_term = _10;
    _12 = pi();
    goto bb1;
bb1:
    _13 = (_12 * denom_term);
    _14 = (_13 * denom_term);
    denom = _14;
    _16 = (a2 / denom);
    return _16;
}

static double geometry_schlick_ggx(double n_dot_v, double roughness) {
    double _ret;
    double _3;
    double r;
    double _5;
    double _6;
    double k;
    double _8;
    double _9;
    double _10;
    double _11;

    _3 = (roughness + 1);
    r = _3;
    _5 = (r * r);
    _6 = (_5 / 8);
    k = _6;
    _8 = (1 - k);
    _9 = (n_dot_v * _8);
    _10 = (_9 + k);
    _11 = (n_dot_v / _10);
    return _11;
}

static double geometry_smith(double n_dot_v, double n_dot_l, double roughness) {
    double _ret;
    double _4;
    double _5;
    double _6;

    _4 = geometry_schlick_ggx(n_dot_v, roughness);
    goto bb1;
bb1:
    _5 = geometry_schlick_ggx(n_dot_l, roughness);
    goto bb2;
bb2:
    _6 = (_4 * _5);
    return _6;
}

static double cook_torrance_specular(double n_dot_h, double n_dot_v, double n_dot_l, double h_dot_v, double roughness, double f0) {
    double _ret;
    double _7;
    double d;
    double _9;
    double f;
    double _11;
    double g;
    double _13;
    double _14;
    double numerator;
    double _16;
    double _17;
    double _18;
    double denominator;
    double _20;

    _7 = distribution_ggx(n_dot_h, roughness);
    goto bb1;
bb1:
    d = _7;
    _9 = fresnel_schlick(h_dot_v, f0);
    goto bb2;
bb2:
    f = _9;
    _11 = geometry_smith(n_dot_v, n_dot_l, roughness);
    goto bb3;
bb3:
    g = _11;
    _13 = (d * f);
    _14 = (_13 * g);
    numerator = _14;
    _16 = (4 * n_dot_v);
    _17 = (_16 * n_dot_l);
    _18 = (_17 + 0.0001);
    denominator = _18;
    _20 = (numerator / denominator);
    return _20;
}

static double pbr_lighting(double n_dot_h, double n_dot_v, double n_dot_l, double h_dot_v, double albedo, double roughness, double metallic) {
    double _ret;
    double _8;
    double _9;
    double _10;
    double _11;
    double f0;
    double _13;
    double specular;
    double _15;
    double ks;
    double _17;
    double _18;
    double _19;
    double kd;
    double _21;
    double _22;
    double _23;
    double diffuse;
    double _25;
    double _26;

    _8 = (1 - metallic);
    _9 = (0.04 * _8);
    _10 = (albedo * metallic);
    _11 = (_9 + _10);
    f0 = _11;
    _13 = cook_torrance_specular(n_dot_h, n_dot_v, n_dot_l, h_dot_v, roughness, f0);
    goto bb1;
bb1:
    specular = _13;
    _15 = fresnel_schlick(h_dot_v, f0);
    goto bb2;
bb2:
    ks = _15;
    _17 = (1 - ks);
    _18 = (1 - metallic);
    _19 = (_17 * _18);
    kd = _19;
    _21 = (kd * albedo);
    _22 = pi();
    goto bb3;
bb3:
    _23 = (_21 / _22);
    diffuse = _23;
    _25 = (diffuse + specular);
    _26 = (_25 * n_dot_l);
    return _26;
}

static double aces_tonemap(double x) {
    double _ret;
    double _2;
    double _3;
    double _4;
    double num;
    double _6;
    double _7;
    double _8;
    double _9;
    double den;
    double _11;
    double _12;

    _2 = (2.51 * x);
    _3 = (_2 + 0.03);
    _4 = (x * _3);
    num = _4;
    _6 = (2.43 * x);
    _7 = (_6 + 0.59);
    _8 = (x * _7);
    _9 = (_8 + 0.14);
    den = _9;
    _11 = (num / den);
    _12 = quanta_clampf(_11, 0, 1);
    goto bb1;
bb1:
    return _12;
}

static double linear_to_srgb(double x) {
    double _ret;
    double _2;
    double _3;
    double _4;

    _2 = (1 / 2.2);
    _3 = pow(x, _2);
    goto bb1;
bb1:
    _4 = quanta_clampf(_3, 0, 1);
    goto bb2;
bb2:
    return _4;
}

static quanta_vec4 fs_pbr(quanta_vec3 inputs) {
    quanta_vec4 _ret;
    double _2;
    double _3;
    double n_dot_l;
    double _5;
    double _6;
    double n_dot_h;
    double _8;
    double _9;
    double h_dot_v;
    double n_dot_v;
    double albedo;
    double roughness;
    double metallic;
    double _15;
    double lit;
    double _17;
    double mapped;
    double _19;
    double final_val;
    quanta_vec4 _21;

    _2 = inputs.x;
    _3 = quanta_clampf(_2, 0, 1);
    goto bb1;
bb1:
    n_dot_l = _3;
    _5 = inputs.y;
    _6 = quanta_clampf(_5, 0, 1);
    goto bb2;
bb2:
    n_dot_h = _6;
    _8 = inputs.z;
    _9 = quanta_clampf(_8, 0, 1);
    goto bb3;
bb3:
    h_dot_v = _9;
    n_dot_v = 0.8;
    albedo = 0.8;
    roughness = 0.4;
    metallic = 0;
    _15 = pbr_lighting(n_dot_h, n_dot_v, n_dot_l, h_dot_v, albedo, roughness, metallic);
    goto bb4;
bb4:
    lit = _15;
    _17 = aces_tonemap(lit);
    goto bb5;
bb5:
    mapped = _17;
    _19 = linear_to_srgb(mapped);
    goto bb6;
bb6:
    final_val = _19;
    _21 = (quanta_vec4){ final_val, final_val, final_val, 1 };
    return _21;
}

int32_t main(void) {
    int32_t _ret;
    int8_t* _1;
    int8_t* _2;
    double _3;
    double f;
    int8_t* _5;
    double _6;
    double f_grazing;
    int8_t* _8;
    double _9;
    double d;
    int8_t* _11;
    double _12;
    double d_off;
    int8_t* _14;
    double _15;
    double g;
    int8_t* _17;
    double _18;
    double dielectric;
    int8_t* _20;
    double _21;
    double metal;
    int8_t* _23;
    double _24;
    double smooth;
    double _26;
    double rough;
    int8_t* _28;
    int8_t* _29;
    int8_t* _30;
    int8_t* _31;

    _1 = __str0;
    printf(_1);
    goto bb1;
bb1:
    _2 = __str1;
    printf(_2);
    goto bb2;
bb2:
    _3 = fresnel_schlick(1, 0.04);
    goto bb3;
bb3:
    f = _3;
    _5 = __str2;
    printf(_5, f);
    goto bb4;
bb4:
    _6 = fresnel_schlick(0, 0.04);
    goto bb5;
bb5:
    f_grazing = _6;
    _8 = __str3;
    printf(_8, f_grazing);
    goto bb6;
bb6:
    _9 = distribution_ggx(1, 0.5);
    goto bb7;
bb7:
    d = _9;
    _11 = __str4;
    printf(_11, d);
    goto bb8;
bb8:
    _12 = distribution_ggx(0.5, 0.5);
    goto bb9;
bb9:
    d_off = _12;
    _14 = __str5;
    printf(_14, d_off);
    goto bb10;
bb10:
    _15 = geometry_smith(0.8, 0.8, 0.5);
    goto bb11;
bb11:
    g = _15;
    _17 = __str6;
    printf(_17, g);
    goto bb12;
bb12:
    _18 = pbr_lighting(0.9, 0.8, 0.7, 0.85, 0.8, 0.4, 0);
    goto bb13;
bb13:
    dielectric = _18;
    _20 = __str7;
    printf(_20, dielectric);
    goto bb14;
bb14:
    _21 = pbr_lighting(0.9, 0.8, 0.7, 0.85, 0.8, 0.3, 1);
    goto bb15;
bb15:
    metal = _21;
    _23 = __str8;
    printf(_23, metal);
    goto bb16;
bb16:
    _24 = pbr_lighting(0.9, 0.8, 0.7, 0.85, 0.8, 0.1, 0);
    goto bb17;
bb17:
    smooth = _24;
    _26 = pbr_lighting(0.9, 0.8, 0.7, 0.85, 0.8, 0.9, 0);
    goto bb18;
bb18:
    rough = _26;
    _28 = __str9;
    printf(_28, smooth);
    goto bb19;
bb19:
    _29 = __str10;
    printf(_29, rough);
    goto bb20;
bb20:
    _30 = __str1;
    printf(_30);
    goto bb21;
bb21:
    _31 = __str11;
    printf(_31);
    goto bb22;
bb22:
    return 0;
}

