// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double fresnel_schlick(double cos_theta, double f0) {
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _3 = (1.0 - f0);
    _4 = (1.0 - cos_theta);
    _5 = pow(_4, 5.0);
    _6 = (_3 * _5);
    _7 = (f0 + _6);
    return _7;
}

double fog_factor(double distance, double density) {
    double _3;
    double exponent;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    _3 = (distance * density);
    exponent = _3;
    _5 = (exponent * exponent);
    _6 = (0.0 - _5);
    _7 = pow(2.718281828, _6);
    _8 = (1.0 - _7);
    _9 = clamp(_8, 0.0, 1.0);
    return _9;
}

vec4 fs_main(vec3 uv) {
    double _2;
    double x;
    double _4;
    double y;
    double _6;
    double _7;
    double s;
    double _9;
    double _10;
    double c;
    double _12;
    double _13;
    double _14;
    double _15;
    double r;
    double _17;
    double _18;
    double f;
    double _20;
    double _21;
    double brightness;
    double _23;
    double _24;
    double fresnel;
    double _26;
    double _27;
    double fog;
    vec4 _29;
    _2 = uv.x;
    x = _2;
    _4 = uv.y;
    y = _4;
    _6 = (x * 3.14159);
    _7 = sin(_6);
    s = _7;
    _9 = (y * 3.14159);
    _10 = cos(_9);
    c = _10;
    _12 = (x * x);
    _13 = (y * y);
    _14 = (_12 + _13);
    _15 = sqrt(_14);
    r = _15;
    _17 = (x * 10.0);
    _18 = floor(_17);
    f = _18;
    _20 = (s * c);
    _21 = abs(_20);
    brightness = _21;
    _23 = clamp(r, 0.0, 1.0);
    _24 = fresnel_schlick(_23, 0.04);
    fresnel = _24;
    _26 = (r * 10.0);
    _27 = fog_factor(_26, 0.1);
    fog = _27;
    _29 = vec4(brightness, fresnel, fog, 1.0);
    return _29;
}

