// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct PanelProfile {
    float gamma;
    float red_x;
    float red_y;
    float green_x;
    float green_y;
    float blue_x;
    float blue_y;
    float max_nits;
};

PanelProfile get_srgb_profile() {
    return { 2.2, 0.64, 0.33, 0.3, 0.6, 0.15, 0.06, 350.0 };
}

PanelProfile get_p3_profile() {
    return { 2.2, 0.68, 0.32, 0.265, 0.69, 0.15, 0.06, 600.0 };
}

PanelProfile get_qd_oled_profile() {
    return { 2.2, 0.68, 0.31, 0.228, 0.715, 0.131, 0.046, 1000.0 };
}

float gamut_area(PanelProfile p) {
    return (0.5 * abs((((p.red_x * (p.green_y - p.blue_y)) + (p.green_x * (p.blue_y - p.red_y))) + (p.blue_x * (p.red_y - p.green_y)))));
}

