// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

struct Lab {
    double l;
    double a;
    double b;
};

double delta_e(Lab a, Lab b) {
    double _3;
    double _4;
    double _5;
    double dl;
    double _7;
    double _8;
    double _9;
    double da;
    double _11;
    double _12;
    double _13;
    double db;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    double _20;
    _3 = a.l;
    _4 = b.l;
    _5 = (_3 - _4);
    dl = _5;
    _7 = a.a;
    _8 = b.a;
    _9 = (_7 - _8);
    da = _9;
    _11 = a.b;
    _12 = b.b;
    _13 = (_11 - _12);
    db = _13;
    _15 = (dl * dl);
    _16 = (da * da);
    _17 = (_15 + _16);
    _18 = (db * db);
    _19 = (_17 + _18);
    _20 = sqrt(_19);
    return _20;
}

Lab simulate_measurement(double target_l, double target_a, double target_b, double error) {
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    Lab _11;
    _5 = (error * 2.0);
    _6 = (target_l + _5);
    _7 = (error * 1.5);
    _8 = (target_a + _7);
    _9 = (error * 1.0);
    _10 = (target_b - _9);
    _11 = Lab(_6, _8, _10);
    return _11;
}

Lab compute_correction(Lab target, Lab measured) {
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    Lab _12;
    _3 = target.l;
    _4 = measured.l;
    _5 = (_3 - _4);
    _6 = target.a;
    _7 = measured.a;
    _8 = (_6 - _7);
    _9 = target.b;
    _10 = measured.b;
    _11 = (_9 - _10);
    _12 = Lab(_5, _8, _11);
    return _12;
}

Lab apply_correction(Lab measured, Lab corr) {
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    Lab _12;
    _3 = measured.l;
    _4 = corr.l;
    _5 = (_3 + _4);
    _6 = measured.a;
    _7 = corr.a;
    _8 = (_6 + _7);
    _9 = measured.b;
    _10 = corr.b;
    _11 = (_9 + _10);
    _12 = Lab(_5, _8, _11);
    return _12;
}

