// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct Lab {
    float l;
    float a;
    float b;
};

float delta_e(Lab a, Lab b) {
    float dl = (a.l - b.l);
    float da = (a.a - b.a);
    float db = (a.b - b.b);
    return sqrt((((dl * dl) + (da * da)) + (db * db)));
}

Lab simulate_measurement(float target_l, float target_a, float target_b, float error) {
    return { (target_l + (error * 2.0)), (target_a + (error * 1.5)), (target_b - (error * 1.0)) };
}

Lab compute_correction(Lab target, Lab measured) {
    return { (target.l - measured.l), (target.a - measured.a), (target.b - measured.b) };
}

Lab apply_correction(Lab measured, Lab corr) {
    return { (measured.l + corr.l), (measured.a + corr.a), (measured.b + corr.b) };
}

