// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct Point {
    float x;
    float y;
};

struct Color {
    float r;
    float g;
    float b;
};

float Point_distance(Point self) {
    return sqrt(((self.x * self.x) + (self.y * self.y)));
}

Point Point_translate(Point self, float dx, float dy) {
    return { (self.x + dx), (self.y + dy) };
}

Point Point_scale(Point self, float factor) {
    return { (self.x * factor), (self.y * factor) };
}

float Color_luminance(Color self) {
    return (((0.2126 * self.r) + (0.7152 * self.g)) + (0.0722 * self.b));
}

Color Color_grayscale(Color self) {
    float l = Color_luminance(self);
    return { l, l, l };
}

