// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct XYZ {
    float x;
    float y;
    float z;
};

struct Lab {
    float l;
    float a;
    float b;
};

struct RGB {
    float r;
    float g;
    float b;
};

float srgb_to_linear(float c) {
    float _4;
    if (c <= 0.04045) {
        return (c / 12.92);
    } else {
        _4 = pow(((c + 0.055) / 1.055), 2.4);
    }
    return _4;
}

float linear_to_srgb(float c) {
    float _4;
    if (c <= 0.0031308) {
        return (c * 12.92);
    } else {
        _4 = ((1.055 * pow(c, (1.0 / 2.4))) - 0.055);
    }
    return _4;
}

XYZ rgb_to_xyz(RGB rgb) {
    float r = srgb_to_linear(rgb.r);
    float g = srgb_to_linear(rgb.g);
    float b = srgb_to_linear(rgb.b);
    return { (((0.4124564 * r) + (0.3575761 * g)) + (0.1804375 * b)), (((0.2126729 * r) + (0.7151522 * g)) + (0.072175 * b)), (((0.0193339 * r) + (0.119192 * g)) + (0.9503041 * b)) };
}

RGB xyz_to_rgb(XYZ xyz) {
    float rl = (((3.2404542 * xyz.x) - (1.5371385 * xyz.y)) - (0.4985314 * xyz.z));
    float gl = ((((-0.969266) * xyz.x) + (1.8760108 * xyz.y)) + (0.041556 * xyz.z));
    float bl = (((0.0556434 * xyz.x) - (0.2040259 * xyz.y)) + (1.0572252 * xyz.z));
    return { linear_to_srgb(rl), linear_to_srgb(gl), linear_to_srgb(bl) };
}

float lab_f(float t) {
    float _9;
    float delta = (6.0 / 29.0);
    if (t > ((delta * delta) * delta)) {
        return pow(t, (1.0 / 3.0));
    } else {
        _9 = ((t / ((3.0 * delta) * delta)) + (4.0 / 29.0));
    }
    return _9;
}

Lab xyz_to_lab(XYZ xyz) {
    float fx = lab_f((xyz.x / 0.95047));
    float fy = lab_f((xyz.y / 1.0));
    float fz = lab_f((xyz.z / 1.08883));
    return { ((116.0 * fy) - 16.0), (500.0 * (fx - fy)), (200.0 * (fy - fz)) };
}

Lab rgb_to_lab(RGB rgb) {
    return xyz_to_lab(rgb_to_xyz(rgb));
}

