// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

struct XYZ {
    double x;
    double y;
    double z;
};

struct Lab {
    double l;
    double a;
    double b;
};

struct RGB {
    double r;
    double g;
    double b;
};

double srgb_to_linear(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = (c <= 0.04045);
    if (_2) {
        _3 = (c / 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = (c + 0.055);
        _6 = (_5 / 1.055);
        _7 = pow(_6, 2.4);
        _4 = _7;
    }
    return _4;
}

double linear_to_srgb(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    _2 = (c <= 0.0031308);
    if (_2) {
        _3 = (c * 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = (1.0 / 2.4);
        _6 = pow(c, _5);
        _7 = (1.055 * _6);
        _8 = (_7 - 0.055);
        _4 = _8;
    }
    return _4;
}

XYZ rgb_to_xyz(RGB rgb) {
    double _2;
    double _3;
    double r;
    double _5;
    double _6;
    double g;
    double _8;
    double _9;
    double b;
    double _11;
    double _12;
    double _13;
    double _14;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    double _20;
    double _21;
    double _22;
    double _23;
    double _24;
    double _25;
    XYZ _26;
    _2 = rgb.r;
    _3 = srgb_to_linear(_2);
    r = _3;
    _5 = rgb.g;
    _6 = srgb_to_linear(_5);
    g = _6;
    _8 = rgb.b;
    _9 = srgb_to_linear(_8);
    b = _9;
    _11 = (0.4124564 * r);
    _12 = (0.3575761 * g);
    _13 = (_11 + _12);
    _14 = (0.1804375 * b);
    _15 = (_13 + _14);
    _16 = (0.2126729 * r);
    _17 = (0.7151522 * g);
    _18 = (_16 + _17);
    _19 = (0.072175 * b);
    _20 = (_18 + _19);
    _21 = (0.0193339 * r);
    _22 = (0.119192 * g);
    _23 = (_21 + _22);
    _24 = (0.9503041 * b);
    _25 = (_23 + _24);
    _26 = XYZ(_15, _20, _25);
    return _26;
}

RGB xyz_to_rgb(XYZ xyz) {
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double rl;
    double _11;
    double _12;
    double _13;
    double _14;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    double gl;
    double _21;
    double _22;
    double _23;
    double _24;
    double _25;
    double _26;
    double _27;
    double _28;
    double bl;
    double _30;
    double _31;
    double _32;
    RGB _33;
    _2 = xyz.x;
    _3 = (3.2404542 * _2);
    _4 = xyz.y;
    _5 = (1.5371385 * _4);
    _6 = (_3 - _5);
    _7 = xyz.z;
    _8 = (0.4985314 * _7);
    _9 = (_6 - _8);
    rl = _9;
    _11 = (-0.969266);
    _12 = xyz.x;
    _13 = (_11 * _12);
    _14 = xyz.y;
    _15 = (1.8760108 * _14);
    _16 = (_13 + _15);
    _17 = xyz.z;
    _18 = (0.041556 * _17);
    _19 = (_16 + _18);
    gl = _19;
    _21 = xyz.x;
    _22 = (0.0556434 * _21);
    _23 = xyz.y;
    _24 = (0.2040259 * _23);
    _25 = (_22 - _24);
    _26 = xyz.z;
    _27 = (1.0572252 * _26);
    _28 = (_25 + _27);
    bl = _28;
    _30 = linear_to_srgb(rl);
    _31 = linear_to_srgb(gl);
    _32 = linear_to_srgb(bl);
    _33 = RGB(_30, _31, _32);
    return _33;
}

double lab_f(double t) {
    double _2;
    double delta;
    double _4;
    double _5;
    bool _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    double _14;
    _2 = (6.0 / 29.0);
    delta = _2;
    _4 = (delta * delta);
    _5 = (_4 * delta);
    _6 = (t > _5);
    if (_6) {
        _7 = (1.0 / 3.0);
        _8 = pow(t, _7);
        _9 = _8;
        return _9;
    } else {
        _10 = (3.0 * delta);
        _11 = (_10 * delta);
        _12 = (t / _11);
        _13 = (4.0 / 29.0);
        _14 = (_12 + _13);
        _9 = _14;
    }
    return _9;
}

Lab xyz_to_lab(XYZ xyz) {
    double _2;
    double _3;
    double _4;
    double fx;
    double _6;
    double _7;
    double _8;
    double fy;
    double _10;
    double _11;
    double _12;
    double fz;
    double _14;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    Lab _20;
    _2 = xyz.x;
    _3 = (_2 / 0.95047);
    _4 = lab_f(_3);
    fx = _4;
    _6 = xyz.y;
    _7 = (_6 / 1.0);
    _8 = lab_f(_7);
    fy = _8;
    _10 = xyz.z;
    _11 = (_10 / 1.08883);
    _12 = lab_f(_11);
    fz = _12;
    _14 = (116.0 * fy);
    _15 = (_14 - 16.0);
    _16 = (fx - fy);
    _17 = (500.0 * _16);
    _18 = (fy - fz);
    _19 = (200.0 * _18);
    _20 = Lab(_15, _17, _19);
    return _20;
}

Lab rgb_to_lab(RGB rgb) {
    XYZ _2;
    Lab _3;
    _2 = rgb_to_xyz(rgb);
    _3 = xyz_to_lab(_2);
    return _3;
}

