// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct Lab {
    float l;
    float a;
    float b;
};

float delta_e_76(Lab a, Lab b) {
    float dl = (a.l - b.l);
    float da = (a.a - b.a);
    float db = (a.b - b.b);
    return sqrt((((dl * dl) + (da * da)) + (db * db)));
}

float delta_e_94(Lab a, Lab b) {
    float _42;
    float dl = (a.l - b.l);
    float c1 = sqrt(((a.a * a.a) + (a.b * a.b)));
    float c2 = sqrt(((b.a * b.a) + (b.b * b.b)));
    float dc = (c1 - c2);
    float da = (a.a - b.a);
    float db = (a.b - b.b);
    float dh_sq = (((da * da) + (db * db)) - (dc * dc));
    if (dh_sq > 0.0) {
        _42 = dh_sq;
        float dh_sq_safe = _42;
        float sl = 1.0;
        float sc = (1.0 + (0.045 * c1));
        float sh = (1.0 + (0.015 * c1));
        return sqrt(((((dl / sl) * (dl / sl)) + ((dc / sc) * (dc / sc))) + (dh_sq_safe / (sh * sh))));
    } else {
        _42 = 0.0;
    }
    return sqrt(((((dl / sl) * (dl / sl)) + ((dc / sc) * (dc / sc))) + (dh_sq_safe / (sh * sh))));
}

float delta_e_2000(Lab lab1, Lab lab2) {
    float l1 = lab1.l;
    float a1 = lab1.a;
    float b1 = lab1.b;
    float l2 = lab2.l;
    float a2 = lab2.a;
    float b2 = lab2.b;
    float c1 = sqrt(((a1 * a1) + (b1 * b1)));
    float c2 = sqrt(((a2 * a2) + (b2 * b2)));
    float c_avg = ((c1 + c2) / 2.0);
    float c_avg7 = pow(c_avg, 7.0);
    float g = (0.5 * (1.0 - sqrt((c_avg7 / (c_avg7 + pow(25.0, 7.0))))));
    float a1p = (a1 * (1.0 + g));
    float a2p = (a2 * (1.0 + g));
    float c1p = sqrt(((a1p * a1p) + (b1 * b1)));
    float c2p = sqrt(((a2p * a2p) + (b2 * b2)));
    float dl = (l2 - l1);
    float dc = (c2p - c1p);
    float l_avg = ((l1 + l2) / 2.0);
    float c_avg_p = ((c1p + c2p) / 2.0);
    float sl = (1.0 + (((0.015 * (l_avg - 50.0)) * (l_avg - 50.0)) / sqrt((20.0 + ((l_avg - 50.0) * (l_avg - 50.0))))));
    float sc = (1.0 + (0.045 * c_avg_p));
    float sh = (1.0 + (0.015 * c_avg_p));
    return sqrt((((dl / sl) * (dl / sl)) + ((dc / sc) * (dc / sc))));
}

