// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float clamp01(float x) {
    float _3;
    float _5;
    if (x < 0.0) {
        return 0.0;
    } else {
        if (x > 1.0) {
            _5 = 1.0;
            _3 = _5;
        } else {
            _5 = x;
        }
    }
    return _3;
}

float reinhard(float x) {
    return (x / (1.0 + x));
}

float reinhard_extended(float x, float white) {
    float num = (x * (1.0 + (x / (white * white))));
    return (num / (1.0 + x));
}

float aces_filmic(float x) {
    float a = 2.51;
    float b = 0.03;
    float c = 2.43;
    float d = 0.59;
    float e = 0.14;
    return clamp01(((x * ((a * x) + b)) / ((x * ((c * x) + d)) + e)));
}

float aces_hill(float x) {
    float a = 0.0245786;
    float b = 0.000090537;
    float c = 0.983729;
    float d = 0.432951;
    float e = 0.238081;
    return clamp01((((x * (x + a)) - b) / ((x * ((c * x) + d)) + e)));
}

float hable_partial(float x) {
    float a = 0.15;
    float b = 0.5;
    float c = 0.1;
    float d = 0.2;
    float e = 0.02;
    float f = 0.3;
    return ((((x * ((a * x) + (c * b))) + (d * e)) / ((x * ((a * x) + b)) + (d * f))) - (e / f));
}

float hable(float x) {
    float exposure_bias = 2.0;
    float curr = hable_partial((x * exposure_bias));
    float w = hable_partial(11.2);
    return (curr / w);
}

float agx_default(float x) {
    float _3;
    int _9;
    if (x < 0.0) {
        _3 = 0.0;
        float x_clamped = _3;
        if (x_clamped > 0.0) {
            _9 = (log(x_clamped) / log(2.0));
            int lx = _9;
            int val = ((lx - (-12.47393)) / (4.026069 - (-12.47393)));
            return clamp01(val);
        } else {
            _9 = (-14.0);
        }
    } else {
        _3 = x;
    }
    return clamp01(val);
}

