// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct XYZ {
    float x;
    float y;
    float z;
};

float bradford_forward_r(XYZ xyz) {
    return (((0.8951 * xyz.x) + (0.2664 * xyz.y)) - (0.1614 * xyz.z));
}

float bradford_forward_g(XYZ xyz) {
    return ((((-0.7502) * xyz.x) + (1.7135 * xyz.y)) + (0.0367 * xyz.z));
}

float bradford_forward_b(XYZ xyz) {
    return (((0.0389 * xyz.x) - (0.0685 * xyz.y)) + (1.0296 * xyz.z));
}

float bradford_inverse_x(float r, float g, float b) {
    return (((0.987 * r) - (0.1471 * g)) + (0.16 * b));
}

float bradford_inverse_y(float r, float g, float b) {
    return (((0.4323 * r) + (0.5184 * g)) + (0.0493 * b));
}

float bradford_inverse_z(float r, float g, float b) {
    return ((((-0.0085) * r) + (0.04 * g)) + (0.9685 * b));
}

float d65_x() {
    return 0.95047;
}

float d65_y() {
    return 1.0;
}

float d65_z() {
    return 1.08883;
}

float d50_x() {
    return 0.96422;
}

float d50_y() {
    return 1.0;
}

float d50_z() {
    return 0.82521;
}

XYZ adapt_bradford(XYZ xyz, XYZ src, XYZ dst) {
    float src_r = bradford_forward_r(src);
    float src_g = bradford_forward_g(src);
    float src_b = bradford_forward_b(src);
    float dst_r = bradford_forward_r(dst);
    float dst_g = bradford_forward_g(dst);
    float dst_b = bradford_forward_b(dst);
    float in_r = bradford_forward_r(xyz);
    float in_g = bradford_forward_g(xyz);
    float in_b = bradford_forward_b(xyz);
    float adapted_r = (in_r * (dst_r / src_r));
    float adapted_g = (in_g * (dst_g / src_g));
    float adapted_b = (in_b * (dst_b / src_b));
    return { bradford_inverse_x(adapted_r, adapted_g, adapted_b), bradford_inverse_y(adapted_r, adapted_g, adapted_b), bradford_inverse_z(adapted_r, adapted_g, adapted_b) };
}

