// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

struct Dual {
    double val;
    double deriv;
};

Dual Dual_add(Dual self, Dual other) {
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    Dual _9;
    _3 = self.val;
    _4 = other.val;
    _5 = (_3 + _4);
    _6 = self.deriv;
    _7 = other.deriv;
    _8 = (_6 + _7);
    _9 = Dual(_5, _8);
    return _9;
}

Dual Dual_sub(Dual self, Dual other) {
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    Dual _9;
    _3 = self.val;
    _4 = other.val;
    _5 = (_3 - _4);
    _6 = self.deriv;
    _7 = other.deriv;
    _8 = (_6 - _7);
    _9 = Dual(_5, _8);
    return _9;
}

Dual Dual_mul(Dual self, Dual other) {
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    Dual _13;
    _3 = self.val;
    _4 = other.val;
    _5 = (_3 * _4);
    _6 = self.deriv;
    _7 = other.val;
    _8 = (_6 * _7);
    _9 = self.val;
    _10 = other.deriv;
    _11 = (_9 * _10);
    _12 = (_8 + _11);
    _13 = Dual(_5, _12);
    return _13;
}

Dual Dual_div(Dual self, Dual other) {
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    double _14;
    double _15;
    double _16;
    Dual _17;
    _3 = self.val;
    _4 = other.val;
    _5 = (_3 / _4);
    _6 = self.deriv;
    _7 = other.val;
    _8 = (_6 * _7);
    _9 = self.val;
    _10 = other.deriv;
    _11 = (_9 * _10);
    _12 = (_8 - _11);
    _13 = other.val;
    _14 = other.val;
    _15 = (_13 * _14);
    _16 = (_12 / _15);
    _17 = Dual(_5, _16);
    return _17;
}

Dual dual_var(double x) {
    Dual _2;
    _2 = Dual(x, 1.0);
    return _2;
}

Dual dual_const(double x) {
    Dual _2;
    _2 = Dual(x, 0.0);
    return _2;
}

Dual dual_sin(Dual d) {
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    Dual _8;
    _2 = d.val;
    _3 = sin(_2);
    _4 = d.deriv;
    _5 = d.val;
    _6 = cos(_5);
    _7 = (_4 * _6);
    _8 = Dual(_3, _7);
    return _8;
}

Dual dual_cos(Dual d) {
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    Dual _9;
    _2 = d.val;
    _3 = cos(_2);
    _4 = d.deriv;
    _5 = d.val;
    _6 = sin(_5);
    _7 = (_4 * _6);
    _8 = (0.0 - _7);
    _9 = Dual(_3, _8);
    return _9;
}

Dual dual_pow2(Dual d) {
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    Dual _9;
    _2 = d.val;
    _3 = d.val;
    _4 = (_2 * _3);
    _5 = d.val;
    _6 = (2.0 * _5);
    _7 = d.deriv;
    _8 = (_6 * _7);
    _9 = Dual(_4, _8);
    return _9;
}

