// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct Dual {
    float val;
    float deriv;
};

Dual Dual_add(Dual self, Dual other) {
    return { (self.val + other.val), (self.deriv + other.deriv) };
}

Dual Dual_sub(Dual self, Dual other) {
    return { (self.val - other.val), (self.deriv - other.deriv) };
}

Dual Dual_mul(Dual self, Dual other) {
    return { (self.val * other.val), ((self.deriv * other.val) + (self.val * other.deriv)) };
}

Dual Dual_div(Dual self, Dual other) {
    return { (self.val / other.val), (((self.deriv * other.val) - (self.val * other.deriv)) / (other.val * other.val)) };
}

Dual dual_var(float x) {
    return { x, 1.0 };
}

Dual dual_const(float x) {
    return { x, 0.0 };
}

Dual dual_sin(Dual d) {
    return { sin(d.val), (d.deriv * cos(d.val)) };
}

Dual dual_cos(Dual d) {
    return { cos(d.val), (0.0 - (d.deriv * sin(d.val))) };
}

Dual dual_pow2(Dual d) {
    return { (d.val * d.val), ((2.0 * d.val) * d.deriv) };
}

