// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float mae(float[5] actual, float[5] predicted) {
    float sum;
    int i;
    float _12;
    sum = 0.0;
    i = 0;
    while (i < 5) {
        float _6 = 0;
        float _7 = 0;
        float diff = (_6 - _7);
        if (diff < 0.0) {
            _12 = (0.0 - diff);
            float absdiff = _12;
            sum = (sum + absdiff);
            i = (i + 1);
        } else {
            _12 = diff;
        }
    }
    return (sum / 5.0);
}

float mse(float[5] actual, float[5] predicted) {
    float sum;
    int i;
    sum = 0.0;
    i = 0;
    while (i < 5) {
        float _6 = 0;
        float _7 = 0;
        float diff = (_6 - _7);
        sum = (sum + (diff * diff));
        i = (i + 1);
    }
    return (sum / 5.0);
}

float rmse(float[5] actual, float[5] predicted) {
    return sqrt(mse(actual, predicted));
}

float mape(float[5] actual, float[5] predicted) {
    float sum;
    int i;
    float _12;
    sum = 0.0;
    i = 0;
    while (i < 5) {
        float _6 = 0;
        float _7 = 0;
        float diff = (_6 - _7);
        if (diff < 0.0) {
            _12 = (0.0 - diff);
            float absdiff = _12;
            float _14 = 0;
            if (_14 != 0.0) {
                float _16 = 0;
                sum = (sum + (absdiff / _16));
                i = (i + 1);
            } else {
            }
        } else {
            _12 = diff;
        }
    }
    return ((sum / 5.0) * 100.0);
}

float r_squared(float[5] actual, float[5] predicted) {
    float mean;
    int i;
    float ss_res;
    float ss_tot;
    mean = 0.0;
    i = 0;
    while (i < 5) {
        float _6 = 0;
        mean = (mean + _6);
        i = (i + 1);
    }
    mean = (mean / 5.0);
    ss_res = 0.0;
    ss_tot = 0.0;
    i = 0;
    while (i < 5) {
        float _13 = 0;
        float _14 = 0;
        float res = (_13 - _14);
        ss_res = (ss_res + (res * res));
        float _19 = 0;
        float tot = (_19 - mean);
        ss_tot = (ss_tot + (tot * tot));
        i = (i + 1);
    }
    return (1.0 - (ss_res / ss_tot));
}

