// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float estimate_ar1(float[10] data) {
    float mean;
    int i;
    float c0;
    float c1;
    float _32;
    mean = 0.0;
    i = 0;
    while (i < 10) {
        float _5 = 0;
        mean = (mean + _5);
        i = (i + 1);
    }
    mean = (mean / 10.0);
    c0 = 0.0;
    c1 = 0.0;
    i = 0;
    while (i < 10) {
        float _12 = 0;
        float _14 = 0;
        c0 = (c0 + ((_12 - mean) * (_14 - mean)));
        if (i > 0) {
            float _19 = 0;
            int _21 = (i - 1);
            float _22 = 0;
            c1 = (c1 + ((_19 - mean) * (_22 - mean)));
            i = (i + 1);
        } else {
        }
    }
    c0 = (c0 / 10.0);
    c1 = (c1 / 9.0);
    if (c0 > 0.0001) {
        return (c1 / c0);
    } else {
        _32 = 0.0;
    }
    return _32;
}

float forecast_ar1(float last_val, float mean, float phi, int steps) {
    float forecast;
    int s;
    forecast = last_val;
    s = 0;
    while (s < steps) {
        forecast = (mean + (phi * (forecast - mean)));
        s = (s + 1);
    }
    return forecast;
}

