// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float moving_average_at6(float[12] data) {
    float _2 = 0;
    float _3 = 0;
    float _5 = 0;
    float _7 = 0;
    float _9 = 0;
    float sum = ((((_2 + _3) + _5) + _7) + _9);
    return (sum / 5.0);
}

