// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double sma5(double[10] data) {
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    _2 = 0;
    _3 = 0;
    _4 = (_2 + _3);
    _5 = 0;
    _6 = (_4 + _5);
    _7 = 0;
    _8 = (_6 + _7);
    _9 = 0;
    _10 = (_8 + _9);
    _11 = (_10 / 5.0);
    return _11;
}

double sma3_at4(double[10] data) {
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = 0;
    _3 = 0;
    _4 = (_2 + _3);
    _5 = 0;
    _6 = (_4 + _5);
    _7 = (_6 / 3.0);
    return _7;
}

double sma3_last(double[10] data) {
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = 0;
    _3 = 0;
    _4 = (_2 + _3);
    _5 = 0;
    _6 = (_4 + _5);
    _7 = (_6 / 3.0);
    return _7;
}

double ema5(double[10] data) {
    double _2;
    double alpha;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    double result;
    int i;
    bool _16;
    double _17;
    double _18;
    double _19;
    double _20;
    double _21;
    int _22;
    _2 = (2.0 / 6.0);
    alpha = _2;
    _4 = 0;
    _5 = 0;
    _6 = (_4 + _5);
    _7 = 0;
    _8 = (_6 + _7);
    _9 = 0;
    _10 = (_8 + _9);
    _11 = 0;
    _12 = (_10 + _11);
    _13 = (_12 / 5.0);
    result = _13;
    i = 5;
    _16 = (i < 10);
    while (_16) {
        _17 = 0;
        _18 = (alpha * _17);
        _19 = (1.0 - alpha);
        _20 = (_19 * result);
        _21 = (_18 + _20);
        result = _21;
        _22 = (i + 1);
        i = _22;
    }
    return result;
}

double rsi5(double[10] data) {
    double avg_gain;
    double avg_loss;
    int i;
    bool _5;
    double _6;
    int _7;
    double _8;
    double _9;
    double change;
    bool _11;
    double _12;
    double _14;
    int _15;
    double _16;
    double _17;
    bool _18;
    double _19;
    int _20;
    double _21;
    double _22;
    double change;
    bool _24;
    double _25;
    double _26;
    double _27;
    double _28;
    double _29;
    double _31;
    double _32;
    double _33;
    double _34;
    double _35;
    int _36;
    bool _37;
    double _38;
    double _39;
    double rs;
    double _41;
    double _42;
    double _43;
    avg_gain = 0.0;
    avg_loss = 0.0;
    i = 1;
    _5 = (i <= 5);
    while (_5) {
        _6 = 0;
        _7 = (i - 1);
        _8 = 0;
        _9 = (_6 - _8);
        change = _9;
        _11 = (change > 0.0);
        if (_11) {
            _12 = (avg_gain + change);
            avg_gain = _12;
            _15 = (i + 1);
            i = _15;
        } else {
            _14 = (avg_loss - change);
            avg_loss = _14;
        }
    }
    _16 = (avg_gain / 5.0);
    avg_gain = _16;
    _17 = (avg_loss / 5.0);
    avg_loss = _17;
    _18 = (i < 10);
    while (_18) {
        _19 = 0;
        _20 = (i - 1);
        _21 = 0;
        _22 = (_19 - _21);
        change = _22;
        _24 = (change > 0.0);
        if (_24) {
            _25 = (avg_gain * 4.0);
            _26 = (_25 + change);
            _27 = (_26 / 5.0);
            avg_gain = _27;
            _28 = (avg_loss * 4.0);
            _29 = (_28 / 5.0);
            avg_loss = _29;
            _36 = (i + 1);
            i = _36;
        } else {
            _31 = (avg_gain * 4.0);
            _32 = (_31 / 5.0);
            avg_gain = _32;
            _33 = (avg_loss * 4.0);
            _34 = (_33 - change);
            _35 = (_34 / 5.0);
            avg_loss = _35;
        }
    }
    _37 = (avg_loss < 0.0001);
    if (_37) {
        _38 = 100.0;
        return _38;
    } else {
        _39 = (avg_gain / avg_loss);
        rs = _39;
        _41 = (1.0 + rs);
        _42 = (100.0 / _41);
        _43 = (100.0 - _42);
        _38 = _43;
    }
    return _38;
}

