// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float sma5(float[10] data) {
    float _2 = 0;
    float _3 = 0;
    float _5 = 0;
    float _7 = 0;
    float _9 = 0;
    return (((((_2 + _3) + _5) + _7) + _9) / 5.0);
}

float sma3_at4(float[10] data) {
    float _2 = 0;
    float _3 = 0;
    float _5 = 0;
    return (((_2 + _3) + _5) / 3.0);
}

float sma3_last(float[10] data) {
    float _2 = 0;
    float _3 = 0;
    float _5 = 0;
    return (((_2 + _3) + _5) / 3.0);
}

float ema5(float[10] data) {
    float result;
    int i;
    float alpha = (2.0 / 6.0);
    float _4 = 0;
    float _5 = 0;
    float _7 = 0;
    float _9 = 0;
    float _11 = 0;
    result = (((((_4 + _5) + _7) + _9) + _11) / 5.0);
    i = 5;
    while (i < 10) {
        float _17 = 0;
        result = ((alpha * _17) + ((1.0 - alpha) * result));
        i = (i + 1);
    }
    return result;
}

float rsi5(float[10] data) {
    float avg_gain;
    float avg_loss;
    int i;
    float _38;
    avg_gain = 0.0;
    avg_loss = 0.0;
    i = 1;
    while (i <= 5) {
        float _6 = 0;
        int _7 = (i - 1);
        float _8 = 0;
        float change = (_6 - _8);
        if (change > 0.0) {
            avg_gain = (avg_gain + change);
            i = (i + 1);
        } else {
            avg_loss = (avg_loss - change);
        }
    }
    avg_gain = (avg_gain / 5.0);
    avg_loss = (avg_loss / 5.0);
    while (i < 10) {
        float _19 = 0;
        int _20 = (i - 1);
        float _21 = 0;
        float change = (_19 - _21);
        if (change > 0.0) {
            avg_gain = (((avg_gain * 4.0) + change) / 5.0);
            avg_loss = ((avg_loss * 4.0) / 5.0);
            i = (i + 1);
        } else {
            avg_gain = ((avg_gain * 4.0) / 5.0);
            avg_loss = (((avg_loss * 4.0) - change) / 5.0);
        }
    }
    if (avg_loss < 0.0001) {
        return 100.0;
    } else {
        float rs = (avg_gain / avg_loss);
        _38 = (100.0 - (100.0 / (1.0 + rs)));
    }
    return _38;
}

