// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float daily_return(float[10] prices, int i) {
    float _4;
    if (i == 0) {
        return 0.0;
    } else {
        float _5 = 0;
        int _6 = (i - 1);
        float _7 = 0;
        int _9 = (i - 1);
        float _10 = 0;
        _4 = ((_5 - _7) / _10);
    }
    return _4;
}

float mean_return(float[10] prices) {
    float sum;
    int i;
    sum = 0.0;
    i = 1;
    while (i < 10) {
        sum = (sum + daily_return(prices, i));
        i = (i + 1);
    }
    return (sum / 9.0);
}

float std_return(float[10] prices) {
    float sum_sq;
    int i;
    float mean = mean_return(prices);
    sum_sq = 0.0;
    i = 1;
    while (i < 10) {
        float diff = (daily_return(prices, i) - mean);
        sum_sq = (sum_sq + (diff * diff));
        i = (i + 1);
    }
    return sqrt((sum_sq / 8.0));
}

float sharpe_ratio(float[10] prices) {
    float _7;
    float mean = mean_return(prices);
    float std = std_return(prices);
    if (std < 0.0001) {
        return 0.0;
    } else {
        _7 = ((mean / std) * sqrt(252.0));
    }
    return _7;
}

float sortino_ratio(float[10] prices) {
    float downside_sq;
    int count;
    int i;
    float _20;
    float mean = mean_return(prices);
    downside_sq = 0.0;
    count = 0;
    i = 1;
    while (i < 10) {
        float ret = daily_return(prices, i);
        if (ret < 0.0) {
            downside_sq = (downside_sq + (ret * ret));
            count = (count + 1);
            i = (i + 1);
        } else {
        }
    }
    if (count > 0) {
        _20 = sqrt((downside_sq / (count * 1.0)));
        float downside_std = _20;
        return ((mean / downside_std) * sqrt(252.0));
    } else {
        _20 = 0.0001;
    }
    return ((mean / downside_std) * sqrt(252.0));
}

float max_drawdown(float[10] prices) {
    float peak;
    float max_dd;
    int i;
    float _2 = 0;
    peak = _2;
    max_dd = 0.0;
    i = 1;
    while (i < 10) {
        float _7 = 0;
        if (_7 > peak) {
            float _9 = 0;
            peak = _9;
            float _11 = 0;
            float dd = ((peak - _11) / peak);
            if (dd > max_dd) {
                max_dd = dd;
                i = (i + 1);
            } else {
            }
        } else {
        }
    }
    return max_dd;
}

