// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct Prediction {
    int model_name;
    float predicted_price;
    float confidence;
};

struct EnsembleResult {
    float weighted_price;
    float signal_strength;
};

EnsembleResult ensemble_predict(Prediction pred1, float w1, Prediction pred2, float w2, Prediction pred3, float w3, float current_price) {
    float _25;
    float _28;
    float total_weight = ((w1 + w2) + w3);
    float weighted = ((((pred1.predicted_price * w1) + (pred2.predicted_price * w2)) + (pred3.predicted_price * w3)) / total_weight);
    float change_pct = ((weighted - current_price) / current_price);
    if (change_pct > 0.005) {
        _25 = change_pct;
        float strength = _25;
        return { weighted, strength };
    } else {
        if (change_pct < (-0.005)) {
            _28 = change_pct;
            _25 = _28;
        } else {
            _28 = 0.0;
        }
    }
    return { weighted, strength };
}

float accuracy_weight(float correct, float total) {
    float _4;
    if (total == 0.0) {
        return 1.0;
    } else {
        float acc = (correct / total);
        _4 = (acc * acc);
    }
    return _4;
}

