// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct PredictionRecord {
    int predicted_up;
    int actual_up;
    int correct;
};

PredictionRecord evaluate(float predicted_price, float actual_price, float current_price) {
    int _5;
    int _8;
    int _11;
    if (predicted_price > current_price) {
        _5 = 1;
        int pred_up = _5;
        if (actual_price > current_price) {
            _8 = 1;
            int act_up = _8;
            if (pred_up == act_up) {
                _11 = 1;
                int correct = _11;
                return { pred_up, act_up, correct };
            } else {
                _11 = 0;
            }
        } else {
            _8 = 0;
        }
    } else {
        _5 = 0;
    }
    return { pred_up, act_up, correct };
}

