// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

struct XYZ {
    double x;
    double y;
    double z;
};

struct Lab {
    double l;
    double a;
    double b;
};

double srgb_to_linear(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = (c <= 0.04045);
    if (_2) {
        _3 = (c / 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = (c + 0.055);
        _6 = (_5 / 1.055);
        _7 = pow(_6, 2.4);
        _4 = _7;
    }
    return _4;
}

XYZ rgb_to_xyz(double r, double g, double b) {
    double _4;
    double rl;
    double _6;
    double gl;
    double _8;
    double bl;
    double _10;
    double _11;
    double _12;
    double _13;
    double _14;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    double _20;
    double _21;
    double _22;
    double _23;
    double _24;
    XYZ _25;
    _4 = srgb_to_linear(r);
    rl = _4;
    _6 = srgb_to_linear(g);
    gl = _6;
    _8 = srgb_to_linear(b);
    bl = _8;
    _10 = (0.4124564 * rl);
    _11 = (0.3575761 * gl);
    _12 = (_10 + _11);
    _13 = (0.1804375 * bl);
    _14 = (_12 + _13);
    _15 = (0.2126729 * rl);
    _16 = (0.7151522 * gl);
    _17 = (_15 + _16);
    _18 = (0.072175 * bl);
    _19 = (_17 + _18);
    _20 = (0.0193339 * rl);
    _21 = (0.119192 * gl);
    _22 = (_20 + _21);
    _23 = (0.9503041 * bl);
    _24 = (_22 + _23);
    _25 = XYZ(_14, _19, _24);
    return _25;
}

double lab_f(double t) {
    double one_third;
    bool _3;
    double _4;
    double _5;
    double _6;
    double _7;
    one_third = 0.333333333;
    _3 = (t > 0.008856);
    if (_3) {
        _4 = pow(t, one_third);
        _5 = _4;
        return _5;
    } else {
        _6 = (t / 0.12842);
        _7 = (_6 + 0.137931);
        _5 = _7;
    }
    return _5;
}

Lab xyz_to_lab(XYZ xyz) {
    double _2;
    double _3;
    double _4;
    double fx;
    double _6;
    double _7;
    double _8;
    double fy;
    double _10;
    double _11;
    double _12;
    double fz;
    double _14;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    Lab _20;
    _2 = xyz.x;
    _3 = (_2 / 0.95047);
    _4 = lab_f(_3);
    fx = _4;
    _6 = xyz.y;
    _7 = (_6 / 1.0);
    _8 = lab_f(_7);
    fy = _8;
    _10 = xyz.z;
    _11 = (_10 / 1.08883);
    _12 = lab_f(_11);
    fz = _12;
    _14 = (116.0 * fy);
    _15 = (_14 - 16.0);
    _16 = (fx - fy);
    _17 = (500.0 * _16);
    _18 = (fy - fz);
    _19 = (200.0 * _18);
    _20 = Lab(_15, _17, _19);
    return _20;
}

double delta_e_76(Lab a, Lab b) {
    double _3;
    double _4;
    double _5;
    double dl;
    double _7;
    double _8;
    double _9;
    double da;
    double _11;
    double _12;
    double _13;
    double db;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    double _20;
    _3 = a.l;
    _4 = b.l;
    _5 = (_3 - _4);
    dl = _5;
    _7 = a.a;
    _8 = b.a;
    _9 = (_7 - _8);
    da = _9;
    _11 = a.b;
    _12 = b.b;
    _13 = (_11 - _12);
    db = _13;
    _15 = (dl * dl);
    _16 = (da * da);
    _17 = (_15 + _16);
    _18 = (db * db);
    _19 = (_17 + _18);
    _20 = sqrt(_19);
    return _20;
}

