// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct XYZ {
    float x;
    float y;
    float z;
};

struct Lab {
    float l;
    float a;
    float b;
};

float srgb_to_linear(float c) {
    float _4;
    if (c <= 0.04045) {
        return (c / 12.92);
    } else {
        _4 = pow(((c + 0.055) / 1.055), 2.4);
    }
    return _4;
}

XYZ rgb_to_xyz(float r, float g, float b) {
    float rl = srgb_to_linear(r);
    float gl = srgb_to_linear(g);
    float bl = srgb_to_linear(b);
    return { (((0.4124564 * rl) + (0.3575761 * gl)) + (0.1804375 * bl)), (((0.2126729 * rl) + (0.7151522 * gl)) + (0.072175 * bl)), (((0.0193339 * rl) + (0.119192 * gl)) + (0.9503041 * bl)) };
}

float lab_f(float t) {
    float _5;
    float one_third = 0.333333333;
    if (t > 0.008856) {
        return pow(t, one_third);
    } else {
        _5 = ((t / 0.12842) + 0.137931);
    }
    return _5;
}

Lab xyz_to_lab(XYZ xyz) {
    float fx = lab_f((xyz.x / 0.95047));
    float fy = lab_f((xyz.y / 1.0));
    float fz = lab_f((xyz.z / 1.08883));
    return { ((116.0 * fy) - 16.0), (500.0 * (fx - fy)), (200.0 * (fy - fz)) };
}

float delta_e_76(Lab a, Lab b) {
    float dl = (a.l - b.l);
    float da = (a.a - b.a);
    float db = (a.b - b.b);
    return sqrt((((dl * dl) + (da * da)) + (db * db)));
}

