// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float gamma_correct(float c, float gamma) {
    float _4;
    if (c <= 0.0) {
        return 0.0;
    } else {
        _4 = pow(c, gamma);
    }
    return _4;
}

float clamp01(float x) {
    float _3;
    float _5;
    if (x < 0.0) {
        return 0.0;
    } else {
        if (x > 1.0) {
            _5 = 1.0;
            _3 = _5;
        } else {
            _5 = x;
        }
    }
    return _3;
}

float warm_correct(float r, float g, float b) {
    return clamp01((gamma_correct(r, 0.95) * 1.02));
}

float lerp(float a, float b, float t) {
    return (a + ((b - a) * t));
}

