// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float aces_channel(float x) {
    float a = 2.51;
    float b = 0.03;
    float c = 2.43;
    float d = 0.59;
    float e = 0.14;
    float num = (x * ((a * x) + b));
    float den = ((x * ((c * x) + d)) + e);
    float result = (num / den);
    return clamp(result, 0.0, 1.0);
}

float4 fs_tonemap(float4 pos : SV_Position, float3 hdr_color) : SV_Target0 {
    float r = aces_channel(hdr_color.x);
    float g = aces_channel(hdr_color.y);
    float b = aces_channel(hdr_color.z);
    return float4(r, g, b, 1.0);
}

