// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

uniform double ao_radius = 0.01;
uniform double ao_intensity = 1.5;

double hash(double n) {
    double _2;
    double _3;
    double x;
    double _5;
    _2 = sin(n);
    _3 = (_2 * 43758.5453);
    x = _3;
    _5 = fract(x);
    return _5;
}

double hash2(double a, double b) {
    double _3;
    double _4;
    double _5;
    double _6;
    _3 = (a * 127.1);
    _4 = (b * 311.7);
    _5 = (_3 + _4);
    _6 = hash(_5);
    return _6;
}

double sample_offset_x(double i, double uv_x, double uv_y) {
    double _4;
    double _5;
    double _6;
    double _7;
    double angle;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    double dist;
    double _15;
    double _16;
    _4 = (i * 3.17);
    _5 = (uv_x + uv_y);
    _6 = hash2(_4, _5);
    _7 = (_6 * 6.2831853);
    angle = _7;
    _9 = (uv_x * 50.0);
    _10 = (_9 + i);
    _11 = (uv_y * 50.0);
    _12 = hash2(_10, _11);
    _13 = (_12 * ao_radius);
    dist = _13;
    _15 = cos(angle);
    _16 = (_15 * dist);
    return _16;
}

double sample_offset_y(double i, double uv_x, double uv_y) {
    double _4;
    double _5;
    double _6;
    double _7;
    double angle;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    double dist;
    double _15;
    double _16;
    _4 = (i * 3.17);
    _5 = (uv_x + uv_y);
    _6 = hash2(_4, _5);
    _7 = (_6 * 6.2831853);
    angle = _7;
    _9 = (uv_x * 50.0);
    _10 = (_9 + i);
    _11 = (uv_y * 50.0);
    _12 = hash2(_10, _11);
    _13 = (_12 * ao_radius);
    dist = _13;
    _15 = sin(angle);
    _16 = (_15 * dist);
    return _16;
}

double compare_depth(double center_d, double sample_x, double sample_y) {
    vec2 _4;
    double _5;
    double sample_d;
    double _7;
    double diff;
    bool _9;
    double _10;
    int _11;
    double _12;
    double range;
    double _14;
    _4 = vec2(sample_x, sample_y);
    _5 = texture(depthbuffer, _4).r;
    sample_d = _5;
    _7 = (center_d - sample_d);
    diff = _7;
    _9 = (diff > 0.0005);
    if (_9) {
        _10 = abs(diff);
        _11 = (ao_radius / _10);
        _12 = smoothstep(0.0, 1.0, _11);
        range = _12;
        _14 = range;
        return _14;
    } else {
        _14 = 0.0;
    }
    return _14;
}

double compute_ssao(double uv_x, double uv_y) {
    vec2 _3;
    double _4;
    double center_d;
    bool _6;
    double _7;
    double occlusion;
    double i;
    bool _10;
    double _11;
    double ox;
    double _13;
    double oy;
    double _15;
    double _16;
    double _17;
    double _18;
    double _19;
    double _20;
    double _21;
    double _22;
    double ao;
    double _24;
    _3 = vec2(uv_x, uv_y);
    _4 = texture(depthbuffer, _3).r;
    center_d = _4;
    _6 = (center_d > 0.999);
    if (_6) {
        _7 = 1.0;
        return _7;
    } else {
        occlusion = 0.0;
        i = 0.0;
        _10 = (i < 8.0);
        while (_10) {
            _11 = sample_offset_x(i, uv_x, uv_y);
            ox = _11;
            _13 = sample_offset_y(i, uv_x, uv_y);
            oy = _13;
            _15 = (uv_x + ox);
            _16 = (uv_y + oy);
            _17 = compare_depth(center_d, _15, _16);
            _18 = (occlusion + _17);
            occlusion = _18;
            _19 = (i + 1.0);
            i = _19;
        }
        _20 = (occlusion / 8.0);
        _21 = (_20 * ao_intensity);
        _22 = (1.0 - _21);
        ao = _22;
        _24 = clamp(ao, 0.0, 1.0);
        _7 = _24;
    }
    return _7;
}

vec4 PS_AmbientOcclusion(vec2 uv) {
    vec4 _2;
    vec4 color;
    double _4;
    double _5;
    double _6;
    double ao;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    vec4 _14;
    _2 = texture(backbuffer, uv);
    color = _2;
    _4 = uv.x;
    _5 = uv.y;
    _6 = compute_ssao(_4, _5);
    ao = _6;
    _8 = color.x;
    _9 = (_8 * ao);
    _10 = color.y;
    _11 = (_10 * ao);
    _12 = color.z;
    _13 = (_12 * ao);
    _14 = vec4(_9, _11, _13, 1.0);
    return _14;
}

