// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

uniform float blur_radius = 3.0;
uniform float blur_strength = 1.0;

float gaussian_weight(float offset, float sigma) {
    float x = (offset / sigma);
    return (exp(((x * x) * (-0.5))) / (sigma * 2.506628));
}

float blur_horizontal(float uv_x, float uv_y, float pixel_w) {
    float weight_sum;
    float i;
    float total = 0.0;
    weight_sum = 0.0;
    i = (0.0 - blur_radius);
    while (i <= blur_radius) {
        float w = gaussian_weight(i, blur_strength);
        weight_sum = (weight_sum + w);
        i = (i + 1.0);
    }
    return (total / weight_sum);
}

float4 PS_Blur(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float4 color = tex2D(ReShade::BackBuffer, uv);
    float blurred = blur_horizontal(color.x, color.y, 0.001);
    return float4(blurred, blurred, blurred, 1.0);
}

