// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

uniform double blur_radius = 3.0;
uniform double blur_strength = 1.0;

double gaussian_weight(double offset, double sigma) {
    double _3;
    double x;
    double _5;
    double _6;
    double _7;
    int _8;
    double _9;
    int _10;
    _3 = (offset / sigma);
    x = _3;
    _5 = (x * x);
    _6 = (-0.5);
    _7 = (_5 * _6);
    _8 = exp(_7);
    _9 = (sigma * 2.506628);
    _10 = (_8 / _9);
    return _10;
}

double blur_horizontal(double uv_x, double uv_y, double pixel_w) {
    double total;
    double weight_sum;
    double _6;
    double i;
    bool _8;
    double _9;
    double w;
    double _11;
    double _12;
    double _13;
    total = 0.0;
    weight_sum = 0.0;
    _6 = (0.0 - blur_radius);
    i = _6;
    _8 = (i <= blur_radius);
    while (_8) {
        _9 = gaussian_weight(i, blur_strength);
        w = _9;
        _11 = (weight_sum + w);
        weight_sum = _11;
        _12 = (i + 1.0);
        i = _12;
    }
    _13 = (total / weight_sum);
    return _13;
}

vec4 PS_Blur(vec2 uv) {
    vec4 _2;
    vec4 color;
    double _4;
    double _5;
    double _6;
    double blurred;
    vec4 _8;
    _2 = texture(backbuffer, uv);
    color = _2;
    _4 = color.x;
    _5 = color.y;
    _6 = blur_horizontal(_4, _5, 0.001);
    blurred = _6;
    _8 = vec4(blurred, blurred, blurred, 1.0);
    return _8;
}

