// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float select_bright(float x) {
    float _3;
    if (x > 0.5) {
        return 1.0;
    } else {
        _3 = 0.0;
    }
    return _3;
}

float4 fs_main(float4 pos : SV_Position, float3 color) : SV_Target0 {
    float r = select_bright(color.x);
    float g = select_bright(color.y);
    float b = select_bright(color.z);
    return float4(r, g, b, 1.0);
}

