// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double hash(double n) {
    double _2;
    double _3;
    double x;
    double _5;
    _2 = sin(n);
    _3 = (_2 * 43758.5453);
    x = _3;
    _5 = fract(x);
    return _5;
}

double vignette(double uv_x, double uv_y, double strength, double softness) {
    double _5;
    double dx;
    double _7;
    double dy;
    double _9;
    double _10;
    double _11;
    double _12;
    double dist;
    double _14;
    double _15;
    double vig;
    double _17;
    double _18;
    double _19;
    _5 = (uv_x - 0.5);
    dx = _5;
    _7 = (uv_y - 0.5);
    dy = _7;
    _9 = (dx * dx);
    _10 = (dy * dy);
    _11 = (_9 + _10);
    _12 = sqrt(_11);
    dist = _12;
    _14 = (0.5 * softness);
    _15 = smoothstep(0.5, _14, dist);
    vig = _15;
    _17 = (1.0 - vig);
    _18 = (strength * _17);
    _19 = (1.0 - _18);
    return _19;
}

double film_grain(double uv_x, double uv_y, double seed, double amount) {
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double noise;
    double _11;
    double _12;
    double _13;
    double grain;
    _5 = (uv_x * 12.9898);
    _6 = (uv_y * 78.233);
    _7 = (_5 + _6);
    _8 = (_7 + seed);
    _9 = hash(_8);
    noise = _9;
    _11 = (noise - 0.5);
    _12 = (_11 * 2.0);
    _13 = (_12 * amount);
    grain = _13;
    return grain;
}

double lift_gamma_gain(double c, double lift, double gamma, double gain) {
    double _5;
    double _6;
    double _7;
    double lifted;
    double _9;
    double gained;
    double _11;
    double _12;
    double graded;
    bool _14;
    double _15;
    bool _16;
    double _17;
    _5 = (1.0 - lift);
    _6 = (c * _5);
    _7 = (_6 + lift);
    lifted = _7;
    _9 = (lifted * gain);
    gained = _9;
    _11 = (1.0 / gamma);
    _12 = pow(gained, _11);
    graded = _12;
    _14 = (graded < 0.0);
    if (_14) {
        _15 = 0.0;
        return _15;
    } else {
        _16 = (graded > 1.0);
        if (_16) {
            _17 = 1.0;
            _15 = _17;
        } else {
            _17 = graded;
        }
    }
    return _15;
}

double srgb_to_linear(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = (c <= 0.04045);
    if (_2) {
        _3 = (c / 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = (c + 0.055);
        _6 = (_5 / 1.055);
        _7 = pow(_6, 2.4);
        _4 = _7;
    }
    return _4;
}

double linear_to_srgb(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = (c <= 0.0031308);
    if (_2) {
        _3 = (c * 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = pow(c, 0.416667);
        _6 = (1.055 * _5);
        _7 = (_6 - 0.055);
        _4 = _7;
    }
    return _4;
}

double process_pixel(double r, double g, double b, double uv_x, double uv_y, double time) {
    double _7;
    double lin_r;
    double _9;
    double graded;
    double _11;
    double vig;
    double _13;
    double vignetted;
    double _15;
    double grain;
    double _17;
    double _18;
    double grained;
    double _20;
    _7 = srgb_to_linear(r);
    lin_r = _7;
    _9 = lift_gamma_gain(lin_r, 0.02, 0.95, 1.1);
    graded = _9;
    _11 = vignette(uv_x, uv_y, 0.4, 0.6);
    vig = _11;
    _13 = (graded * vig);
    vignetted = _13;
    _15 = film_grain(uv_x, uv_y, time, 0.05);
    grain = _15;
    _17 = (grain * vignetted);
    _18 = (vignetted + _17);
    grained = _18;
    _20 = linear_to_srgb(grained);
    return _20;
}

