// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

uniform double strength = 0.4;
uniform double softness = 0.6;
uniform double grain_amount = 0.05;

double hash(double n) {
    double _2;
    double _3;
    double x;
    double _5;
    _2 = sin(n);
    _3 = (_2 * 43758.5453);
    x = _3;
    _5 = fract(x);
    return _5;
}

double vignette(double uv_x, double uv_y) {
    double _3;
    double dx;
    double _5;
    double dy;
    double _7;
    double _8;
    double _9;
    double _10;
    double dist;
    double _12;
    double _13;
    double vig;
    double _15;
    int _16;
    double _17;
    _3 = (uv_x - 0.5);
    dx = _3;
    _5 = (uv_y - 0.5);
    dy = _5;
    _7 = (dx * dx);
    _8 = (dy * dy);
    _9 = (_7 + _8);
    _10 = sqrt(_9);
    dist = _10;
    _12 = (0.5 * softness);
    _13 = smoothstep(0.5, _12, dist);
    vig = _13;
    _15 = (1.0 - vig);
    _16 = (strength * _15);
    _17 = (1.0 - _16);
    return _17;
}

double film_grain(double uv_x, double uv_y, double seed) {
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double noise;
    double _10;
    double _11;
    double _12;
    _4 = (uv_x * 12.9898);
    _5 = (uv_y * 78.233);
    _6 = (_4 + _5);
    _7 = (_6 + seed);
    _8 = hash(_7);
    noise = _8;
    _10 = (noise - 0.5);
    _11 = (_10 * 2.0);
    _12 = (_11 * grain_amount);
    return _12;
}

vec4 PS_Cinematic(vec2 uv) {
    vec4 _2;
    vec4 color;
    double _4;
    double _5;
    double _6;
    double vig;
    double _8;
    double _9;
    double _10;
    double grain;
    double _12;
    double _13;
    double _14;
    double r;
    double _16;
    double _17;
    double _18;
    double g;
    double _20;
    double _21;
    double _22;
    double b;
    vec4 _24;
    _2 = texture(backbuffer, uv);
    color = _2;
    _4 = color.x;
    _5 = color.y;
    _6 = vignette(_4, _5);
    vig = _6;
    _8 = color.x;
    _9 = color.y;
    _10 = film_grain(_8, _9, 0.0);
    grain = _10;
    _12 = color.x;
    _13 = (_12 * vig);
    _14 = (_13 + grain);
    r = _14;
    _16 = color.y;
    _17 = (_16 * vig);
    _18 = (_17 + grain);
    g = _18;
    _20 = color.z;
    _21 = (_20 * vig);
    _22 = (_21 + grain);
    b = _22;
    _24 = vec4(r, g, b, 1.0);
    return _24;
}

