// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

uniform float strength = 0.4;
uniform float softness = 0.6;
uniform float grain_amount = 0.05;

float hash(float n) {
    float x = (sin(n) * 43758.5453);
    return frac(x);
}

float vignette(float uv_x, float uv_y) {
    float dx = (uv_x - 0.5);
    float dy = (uv_y - 0.5);
    float dist = sqrt(((dx * dx) + (dy * dy)));
    float vig = smoothstep(0.5, (0.5 * softness), dist);
    return (1.0 - (strength * (1.0 - vig)));
}

float film_grain(float uv_x, float uv_y, float seed) {
    float noise = hash((((uv_x * 12.9898) + (uv_y * 78.233)) + seed));
    return (((noise - 0.5) * 2.0) * grain_amount);
}

float4 PS_Cinematic(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float4 color = tex2D(ReShade::BackBuffer, uv);
    float vig = vignette(color.x, color.y);
    float grain = film_grain(color.x, color.y, 0.0);
    float r = ((color.x * vig) + grain);
    float g = ((color.y * vig) + grain);
    float b = ((color.z * vig) + grain);
    return float4(r, g, b, 1.0);
}

