// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float hash(float n) {
    float x = (sin(n) * 43758.5453);
    return frac(x);
}

float vignette(float uv_x, float uv_y, float strength, float softness) {
    float dx = (uv_x - 0.5);
    float dy = (uv_y - 0.5);
    float dist = sqrt(((dx * dx) + (dy * dy)));
    float vig = smoothstep(0.5, (0.5 * softness), dist);
    return (1.0 - (strength * (1.0 - vig)));
}

float film_grain(float uv_x, float uv_y, float seed, float amount) {
    float noise = hash((((uv_x * 12.9898) + (uv_y * 78.233)) + seed));
    return (((noise - 0.5) * 2.0) * amount);
}

float lift_gamma_gain(float c, float lift, float gamma, float gain) {
    float _15;
    float _17;
    float lifted = ((c * (1.0 - lift)) + lift);
    float gained = (lifted * gain);
    float graded = pow(gained, (1.0 / gamma));
    if (graded < 0.0) {
        return 0.0;
    } else {
        if (graded > 1.0) {
            _17 = 1.0;
            _15 = _17;
        } else {
            _17 = graded;
        }
    }
    return _15;
}

float srgb_to_linear(float c) {
    float _4;
    if (c <= 0.04045) {
        return (c / 12.92);
    } else {
        _4 = pow(((c + 0.055) / 1.055), 2.4);
    }
    return _4;
}

float linear_to_srgb(float c) {
    float _4;
    if (c <= 0.0031308) {
        return (c * 12.92);
    } else {
        _4 = ((1.055 * pow(c, 0.416667)) - 0.055);
    }
    return _4;
}

float process_pixel(float r, float g, float b, float uv_x, float uv_y, float time) {
    float lin_r = srgb_to_linear(r);
    float graded = lift_gamma_gain(lin_r, 0.02, 0.95, 1.1);
    float vig = vignette(uv_x, uv_y, 0.4, 0.6);
    float vignetted = (graded * vig);
    float grain = film_grain(uv_x, uv_y, time, 0.05);
    float grained = (vignetted + (grain * vignetted));
    return linear_to_srgb(grained);
}

