// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

uniform float lift = 0.0;
uniform float gamma = 1.0;
uniform float gain = 1.0;
uniform float saturation = 1.0;
uniform float temperature = 0.0;

float srgb_to_linear(float c) {
    float _4;
    if (c <= 0.04045) {
        return (c / 12.92);
    } else {
        _4 = pow(((c + 0.055) / 1.055), 2.4);
    }
    return _4;
}

float linear_to_srgb(float c) {
    float _4;
    if (c <= 0.0031308) {
        return (c * 12.92);
    } else {
        _4 = ((1.055 * pow(c, 0.416667)) - 0.055);
    }
    return _4;
}

float lift_gamma_gain(float c) {
    float lifted = ((c * (1.0 - lift)) + lift);
    float gained = (lifted * gain);
    return pow(gained, (1.0 / gamma));
}

float apply_saturation(float r, float g, float b) {
    float luma = (((r * 0.2126) + (g * 0.7152)) + (b * 0.0722));
    return (luma + ((r - luma) * saturation));
}

float apply_temperature(float r, float b) {
    return (r + (temperature * 0.1));
}

float4 PS_ColorGrade(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float4 color = tex2D(ReShade::BackBuffer, uv);
    float lr = srgb_to_linear(color.x);
    float lg = srgb_to_linear(color.y);
    float lb = srgb_to_linear(color.z);
    float gr = lift_gamma_gain(lr);
    float gg = lift_gamma_gain(lg);
    float gb = lift_gamma_gain(lb);
    float sr = apply_saturation(gr, gg, gb);
    float sg = apply_saturation(gg, gr, gb);
    float sb = apply_saturation(gb, gr, gg);
    float tr = (sr + (temperature * 0.05));
    float tb = (sb - (temperature * 0.05));
    float fr = linear_to_srgb(tr);
    float fg = linear_to_srgb(sg);
    float fb = linear_to_srgb(tb);
    return float4(fr, fg, fb, 1.0);
}

