// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

uniform double lift = 0.0;
uniform double gamma = 1.0;
uniform double gain = 1.0;
uniform double saturation = 1.0;
uniform double temperature = 0.0;

double srgb_to_linear(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = (c <= 0.04045);
    if (_2) {
        _3 = (c / 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = (c + 0.055);
        _6 = (_5 / 1.055);
        _7 = pow(_6, 2.4);
        _4 = _7;
    }
    return _4;
}

double linear_to_srgb(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = (c <= 0.0031308);
    if (_2) {
        _3 = (c * 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = pow(c, 0.416667);
        _6 = (1.055 * _5);
        _7 = (_6 - 0.055);
        _4 = _7;
    }
    return _4;
}

double lift_gamma_gain(double c) {
    double _2;
    double _3;
    double _4;
    double lifted;
    double _6;
    double gained;
    double _8;
    double _9;
    _2 = (1.0 - lift);
    _3 = (c * _2);
    _4 = (_3 + lift);
    lifted = _4;
    _6 = (lifted * gain);
    gained = _6;
    _8 = (1.0 / gamma);
    _9 = pow(gained, _8);
    return _9;
}

double apply_saturation(double r, double g, double b) {
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double luma;
    double _10;
    double _11;
    double _12;
    _4 = (r * 0.2126);
    _5 = (g * 0.7152);
    _6 = (_4 + _5);
    _7 = (b * 0.0722);
    _8 = (_6 + _7);
    luma = _8;
    _10 = (r - luma);
    _11 = (_10 * saturation);
    _12 = (luma + _11);
    return _12;
}

double apply_temperature(double r, double b) {
    int _3;
    double _4;
    _3 = (temperature * 0.1);
    _4 = (r + _3);
    return _4;
}

vec4 PS_ColorGrade(vec2 uv) {
    vec4 _2;
    vec4 color;
    double _4;
    double _5;
    double lr;
    double _7;
    double _8;
    double lg;
    double _10;
    double _11;
    double lb;
    double _13;
    double gr;
    double _15;
    double gg;
    double _17;
    double gb;
    double _19;
    double sr;
    double _21;
    double sg;
    double _23;
    double sb;
    int _25;
    double _26;
    double tr;
    int _28;
    double _29;
    double tb;
    double _31;
    double fr;
    double _33;
    double fg;
    double _35;
    double fb;
    vec4 _37;
    _2 = texture(backbuffer, uv);
    color = _2;
    _4 = color.x;
    _5 = srgb_to_linear(_4);
    lr = _5;
    _7 = color.y;
    _8 = srgb_to_linear(_7);
    lg = _8;
    _10 = color.z;
    _11 = srgb_to_linear(_10);
    lb = _11;
    _13 = lift_gamma_gain(lr);
    gr = _13;
    _15 = lift_gamma_gain(lg);
    gg = _15;
    _17 = lift_gamma_gain(lb);
    gb = _17;
    _19 = apply_saturation(gr, gg, gb);
    sr = _19;
    _21 = apply_saturation(gg, gr, gb);
    sg = _21;
    _23 = apply_saturation(gb, gr, gg);
    sb = _23;
    _25 = (temperature * 0.05);
    _26 = (sr + _25);
    tr = _26;
    _28 = (temperature * 0.05);
    _29 = (sb - _28);
    tb = _29;
    _31 = linear_to_srgb(tr);
    fr = _31;
    _33 = linear_to_srgb(sg);
    fg = _33;
    _35 = linear_to_srgb(tb);
    fb = _35;
    _37 = vec4(fr, fg, fb, 1.0);
    return _37;
}

