// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float srgb_to_linear(float c) {
    float _4;
    if (c <= 0.04045) {
        return (c / 12.92);
    } else {
        float a = ((c + 0.055) / 1.055);
        _4 = pow(a, 2.4);
    }
    return _4;
}

float aces_tonemap(float x) {
    float a = 2.51;
    float b = 0.03;
    float c = 2.43;
    float d = 0.59;
    float e = 0.14;
    float num = (x * ((a * x) + b));
    float den = ((x * ((c * x) + d)) + e);
    return clamp((num / den), 0.0, 1.0);
}

float dot3(float ax, float ay, float az, float bx, float by, float bz) {
    return (((ax * bx) + (ay * by)) + (az * bz));
}

