// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double srgb_to_linear(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double a;
    double _8;
    _2 = (c <= 0.04045);
    if (_2) {
        _3 = (c / 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = (c + 0.055);
        _6 = (_5 / 1.055);
        a = _6;
        _8 = pow(a, 2.4);
        _4 = _8;
    }
    return _4;
}

double aces_tonemap(double x) {
    double a;
    double b;
    double c;
    double d;
    double e;
    double _7;
    double _8;
    double _9;
    double num;
    double _11;
    double _12;
    double _13;
    double _14;
    double den;
    double _16;
    double _17;
    a = 2.51;
    b = 0.03;
    c = 2.43;
    d = 0.59;
    e = 0.14;
    _7 = (a * x);
    _8 = (_7 + b);
    _9 = (x * _8);
    num = _9;
    _11 = (c * x);
    _12 = (_11 + d);
    _13 = (x * _12);
    _14 = (_13 + e);
    den = _14;
    _16 = (num / den);
    _17 = clamp(_16, 0.0, 1.0);
    return _17;
}

double dot3(double ax, double ay, double az, double bx, double by, double bz) {
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    _7 = (ax * bx);
    _8 = (ay * by);
    _9 = (_7 + _8);
    _10 = (az * bz);
    _11 = (_9 + _10);
    return _11;
}

