// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

uniform float focus_distance = 0.3;
uniform float aperture = 0.01;

float circle_of_confusion(float depth) {
    float diff = abs((depth - focus_distance));
    float coc = ((diff * aperture) / focus_distance);
    return clamp(coc, 0.0, 0.02);
}

float blur_sample_r(float color_r, float uv_x, float uv_y, float coc) {
    float total;
    float i;
    total = color_r;
    i = 0.0;
    while (i < 8.0) {
        float angle = (i * 0.7853981);
        float sx = (uv_x + (cos(angle) * coc));
        float sy = (uv_y + (sin(angle) * coc));
        float4 s = tex2D(ReShade::BackBuffer, float2(sx, sy));
        total = (total + s.x);
        i = (i + 1.0);
    }
    return (total / 9.0);
}

float blur_sample_g(float color_g, float uv_x, float uv_y, float coc) {
    float total;
    float i;
    total = color_g;
    i = 0.0;
    while (i < 8.0) {
        float angle = (i * 0.7853981);
        float sx = (uv_x + (cos(angle) * coc));
        float sy = (uv_y + (sin(angle) * coc));
        float4 s = tex2D(ReShade::BackBuffer, float2(sx, sy));
        total = (total + s.y);
        i = (i + 1.0);
    }
    return (total / 9.0);
}

float blur_sample_b(float color_b, float uv_x, float uv_y, float coc) {
    float total;
    float i;
    total = color_b;
    i = 0.0;
    while (i < 8.0) {
        float angle = (i * 0.7853981);
        float sx = (uv_x + (cos(angle) * coc));
        float sy = (uv_y + (sin(angle) * coc));
        float4 s = tex2D(ReShade::BackBuffer, float2(sx, sy));
        total = (total + s.z);
        i = (i + 1.0);
    }
    return (total / 9.0);
}

float4 PS_DepthOfField(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float4 color = tex2D(ReShade::BackBuffer, uv);
    float depth = ReShade::GetLinearizedDepth(uv);
    float coc = circle_of_confusion(depth);
    float r = blur_sample_r(color.x, uv.x, uv.y, coc);
    float g = blur_sample_g(color.y, uv.x, uv.y, coc);
    float b = blur_sample_b(color.z, uv.x, uv.y, coc);
    return float4(r, g, b, 1.0);
}

