// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

uniform double focus_distance = 0.3;
uniform double aperture = 0.01;

double circle_of_confusion(double depth) {
    double _2;
    double _3;
    double diff;
    double _5;
    double _6;
    double coc;
    double _8;
    _2 = (depth - focus_distance);
    _3 = abs(_2);
    diff = _3;
    _5 = (diff * aperture);
    _6 = (_5 / focus_distance);
    coc = _6;
    _8 = clamp(coc, 0.0, 0.02);
    return _8;
}

double blur_sample_r(double color_r, double uv_x, double uv_y, double coc) {
    double total;
    double i;
    bool _7;
    double _8;
    double angle;
    double _10;
    double _11;
    double _12;
    double sx;
    double _14;
    double _15;
    double _16;
    double sy;
    vec2 _18;
    vec4 _19;
    vec4 s;
    double _21;
    double _22;
    double _23;
    double _24;
    total = color_r;
    i = 0.0;
    _7 = (i < 8.0);
    while (_7) {
        _8 = (i * 0.7853981);
        angle = _8;
        _10 = cos(angle);
        _11 = (_10 * coc);
        _12 = (uv_x + _11);
        sx = _12;
        _14 = sin(angle);
        _15 = (_14 * coc);
        _16 = (uv_y + _15);
        sy = _16;
        _18 = vec2(sx, sy);
        _19 = texture(backbuffer, _18);
        s = _19;
        _21 = s.x;
        _22 = (total + _21);
        total = _22;
        _23 = (i + 1.0);
        i = _23;
    }
    _24 = (total / 9.0);
    return _24;
}

double blur_sample_g(double color_g, double uv_x, double uv_y, double coc) {
    double total;
    double i;
    bool _7;
    double _8;
    double angle;
    double _10;
    double _11;
    double _12;
    double sx;
    double _14;
    double _15;
    double _16;
    double sy;
    vec2 _18;
    vec4 _19;
    vec4 s;
    double _21;
    double _22;
    double _23;
    double _24;
    total = color_g;
    i = 0.0;
    _7 = (i < 8.0);
    while (_7) {
        _8 = (i * 0.7853981);
        angle = _8;
        _10 = cos(angle);
        _11 = (_10 * coc);
        _12 = (uv_x + _11);
        sx = _12;
        _14 = sin(angle);
        _15 = (_14 * coc);
        _16 = (uv_y + _15);
        sy = _16;
        _18 = vec2(sx, sy);
        _19 = texture(backbuffer, _18);
        s = _19;
        _21 = s.y;
        _22 = (total + _21);
        total = _22;
        _23 = (i + 1.0);
        i = _23;
    }
    _24 = (total / 9.0);
    return _24;
}

double blur_sample_b(double color_b, double uv_x, double uv_y, double coc) {
    double total;
    double i;
    bool _7;
    double _8;
    double angle;
    double _10;
    double _11;
    double _12;
    double sx;
    double _14;
    double _15;
    double _16;
    double sy;
    vec2 _18;
    vec4 _19;
    vec4 s;
    double _21;
    double _22;
    double _23;
    double _24;
    total = color_b;
    i = 0.0;
    _7 = (i < 8.0);
    while (_7) {
        _8 = (i * 0.7853981);
        angle = _8;
        _10 = cos(angle);
        _11 = (_10 * coc);
        _12 = (uv_x + _11);
        sx = _12;
        _14 = sin(angle);
        _15 = (_14 * coc);
        _16 = (uv_y + _15);
        sy = _16;
        _18 = vec2(sx, sy);
        _19 = texture(backbuffer, _18);
        s = _19;
        _21 = s.z;
        _22 = (total + _21);
        total = _22;
        _23 = (i + 1.0);
        i = _23;
    }
    _24 = (total / 9.0);
    return _24;
}

vec4 PS_DepthOfField(vec2 uv) {
    vec4 _2;
    vec4 color;
    double _4;
    double depth;
    double _6;
    double coc;
    double _8;
    double _9;
    double _10;
    double _11;
    double r;
    double _13;
    double _14;
    double _15;
    double _16;
    double g;
    double _18;
    double _19;
    double _20;
    double _21;
    double b;
    vec4 _23;
    _2 = texture(backbuffer, uv);
    color = _2;
    _4 = texture(depthbuffer, uv).r;
    depth = _4;
    _6 = circle_of_confusion(depth);
    coc = _6;
    _8 = color.x;
    _9 = uv.x;
    _10 = uv.y;
    _11 = blur_sample_r(_8, _9, _10, coc);
    r = _11;
    _13 = color.y;
    _14 = uv.x;
    _15 = uv.y;
    _16 = blur_sample_g(_13, _14, _15, coc);
    g = _16;
    _18 = color.z;
    _19 = uv.x;
    _20 = uv.y;
    _21 = blur_sample_b(_18, _19, _20, coc);
    b = _21;
    _23 = vec4(r, g, b, 1.0);
    return _23;
}

