// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float aces_tonemap(float x) {
    float a = 2.51;
    float b = 0.03;
    float c = 2.43;
    float d = 0.59;
    float e = 0.14;
    float num = (x * ((a * x) + b));
    float den = ((x * ((c * x) + d)) + e);
    return clamp((num / den), 0.0, 1.0);
}

float fresnel(float cos_theta, float f0) {
    return (f0 + ((1.0 - f0) * pow(clamp((1.0 - cos_theta), 0.0, 1.0), 5.0)));
}

float4 fs_postprocess(float4 pos : SV_Position, float3 hdr_color) : SV_Target0 {
    float r = aces_tonemap(hdr_color.x);
    float g = aces_tonemap(hdr_color.y);
    float b = aces_tonemap(hdr_color.z);
    return float4(r, g, b, 1.0);
}

