// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double saturate(double x) {
    bool _2;
    double _3;
    bool _4;
    double _5;
    _2 = (x > 1.0);
    if (_2) {
        _3 = 1.0;
        return _3;
    } else {
        _4 = (x < 0.0);
        if (_4) {
            _5 = 0.0;
            _3 = _5;
        } else {
            _5 = x;
        }
    }
    return _3;
}

vec4 fs_main(vec3 color) {
    double _2;
    double _3;
    double r;
    double _5;
    double _6;
    double g;
    double _8;
    double _9;
    double b;
    vec4 _11;
    _2 = color.x;
    _3 = saturate(_2);
    r = _3;
    _5 = color.y;
    _6 = saturate(_5);
    g = _6;
    _8 = color.z;
    _9 = saturate(_8);
    b = _9;
    _11 = vec4(r, g, b, 1.0);
    return _11;
}

