// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float saturate(float x) {
    float _3;
    float _5;
    if (x > 1.0) {
        return 1.0;
    } else {
        if (x < 0.0) {
            _5 = 0.0;
            _3 = _5;
        } else {
            _5 = x;
        }
    }
    return _3;
}

float4 fs_main(float4 pos : SV_Position, float3 color) : SV_Target0 {
    float r = saturate(color.x);
    float g = saturate(color.y);
    float b = saturate(color.z);
    return float4(r, g, b, 1.0);
}

