// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

vec4 vs_main(vec3 pos) {
    double _2;
    double _3;
    double _4;
    vec4 _5;
    _2 = pos.x;
    _3 = pos.y;
    _4 = pos.z;
    _5 = vec4(_2, _3, _4, 1.0);
    return _5;
}

