// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double pi() {
    return 3.14159265358979;
}

double fresnel_schlick(double cos_theta, double f0) {
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    _3 = (1.0 - f0);
    _4 = (1.0 - cos_theta);
    _5 = clamp(_4, 0.0, 1.0);
    _6 = pow(_5, 5.0);
    _7 = (_3 * _6);
    _8 = (f0 + _7);
    return _8;
}

double distribution_ggx(double n_dot_h, double roughness) {
    double _3;
    double a;
    double _5;
    double a2;
    double _7;
    double _8;
    double _9;
    double _10;
    double denom_term;
    double _12;
    double _13;
    double _14;
    double denom;
    double _16;
    _3 = (roughness * roughness);
    a = _3;
    _5 = (a * a);
    a2 = _5;
    _7 = (n_dot_h * n_dot_h);
    _8 = (a2 - 1.0);
    _9 = (_7 * _8);
    _10 = (_9 + 1.0);
    denom_term = _10;
    _12 = pi();
    _13 = (_12 * denom_term);
    _14 = (_13 * denom_term);
    denom = _14;
    _16 = (a2 / denom);
    return _16;
}

double geometry_schlick_ggx(double n_dot_v, double roughness) {
    double _3;
    double r;
    double _5;
    double _6;
    double k;
    double _8;
    double _9;
    double _10;
    double _11;
    _3 = (roughness + 1.0);
    r = _3;
    _5 = (r * r);
    _6 = (_5 / 8.0);
    k = _6;
    _8 = (1.0 - k);
    _9 = (n_dot_v * _8);
    _10 = (_9 + k);
    _11 = (n_dot_v / _10);
    return _11;
}

double geometry_smith(double n_dot_v, double n_dot_l, double roughness) {
    double _4;
    double _5;
    double _6;
    _4 = geometry_schlick_ggx(n_dot_v, roughness);
    _5 = geometry_schlick_ggx(n_dot_l, roughness);
    _6 = (_4 * _5);
    return _6;
}

double cook_torrance_specular(double n_dot_h, double n_dot_v, double n_dot_l, double h_dot_v, double roughness, double f0) {
    double _7;
    double d;
    double _9;
    double f;
    double _11;
    double g;
    double _13;
    double _14;
    double numerator;
    double _16;
    double _17;
    double _18;
    double denominator;
    double _20;
    _7 = distribution_ggx(n_dot_h, roughness);
    d = _7;
    _9 = fresnel_schlick(h_dot_v, f0);
    f = _9;
    _11 = geometry_smith(n_dot_v, n_dot_l, roughness);
    g = _11;
    _13 = (d * f);
    _14 = (_13 * g);
    numerator = _14;
    _16 = (4.0 * n_dot_v);
    _17 = (_16 * n_dot_l);
    _18 = (_17 + 0.0001);
    denominator = _18;
    _20 = (numerator / denominator);
    return _20;
}

double pbr_lighting(double n_dot_h, double n_dot_v, double n_dot_l, double h_dot_v, double albedo, double roughness, double metallic) {
    double _8;
    double _9;
    double _10;
    double _11;
    double f0;
    double _13;
    double specular;
    double _15;
    double ks;
    double _17;
    double _18;
    double _19;
    double kd;
    double _21;
    double _22;
    double _23;
    double diffuse;
    double _25;
    double _26;
    _8 = (1.0 - metallic);
    _9 = (0.04 * _8);
    _10 = (albedo * metallic);
    _11 = (_9 + _10);
    f0 = _11;
    _13 = cook_torrance_specular(n_dot_h, n_dot_v, n_dot_l, h_dot_v, roughness, f0);
    specular = _13;
    _15 = fresnel_schlick(h_dot_v, f0);
    ks = _15;
    _17 = (1.0 - ks);
    _18 = (1.0 - metallic);
    _19 = (_17 * _18);
    kd = _19;
    _21 = (kd * albedo);
    _22 = pi();
    _23 = (_21 / _22);
    diffuse = _23;
    _25 = (diffuse + specular);
    _26 = (_25 * n_dot_l);
    return _26;
}

double aces_tonemap(double x) {
    double _2;
    double _3;
    double _4;
    double num;
    double _6;
    double _7;
    double _8;
    double _9;
    double den;
    double _11;
    double _12;
    _2 = (2.51 * x);
    _3 = (_2 + 0.03);
    _4 = (x * _3);
    num = _4;
    _6 = (2.43 * x);
    _7 = (_6 + 0.59);
    _8 = (x * _7);
    _9 = (_8 + 0.14);
    den = _9;
    _11 = (num / den);
    _12 = clamp(_11, 0.0, 1.0);
    return _12;
}

double linear_to_srgb(double x) {
    double _2;
    double _3;
    double _4;
    _2 = (1.0 / 2.2);
    _3 = pow(x, _2);
    _4 = clamp(_3, 0.0, 1.0);
    return _4;
}

vec4 fs_pbr(vec3 inputs) {
    double _2;
    double _3;
    double n_dot_l;
    double _5;
    double _6;
    double n_dot_h;
    double _8;
    double _9;
    double h_dot_v;
    double n_dot_v;
    double albedo;
    double roughness;
    double metallic;
    double _15;
    double lit;
    double _17;
    double mapped;
    double _19;
    double final_val;
    vec4 _21;
    _2 = inputs.x;
    _3 = clamp(_2, 0.0, 1.0);
    n_dot_l = _3;
    _5 = inputs.y;
    _6 = clamp(_5, 0.0, 1.0);
    n_dot_h = _6;
    _8 = inputs.z;
    _9 = clamp(_8, 0.0, 1.0);
    h_dot_v = _9;
    n_dot_v = 0.8;
    albedo = 0.8;
    roughness = 0.4;
    metallic = 0.0;
    _15 = pbr_lighting(n_dot_h, n_dot_v, n_dot_l, h_dot_v, albedo, roughness, metallic);
    lit = _15;
    _17 = aces_tonemap(lit);
    mapped = _17;
    _19 = linear_to_srgb(mapped);
    final_val = _19;
    _21 = vec4(final_val, final_val, final_val, 1.0);
    return _21;
}

