// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float pi() {
    return 3.14159265358979;
}

float fresnel_schlick(float cos_theta, float f0) {
    return (f0 + ((1.0 - f0) * pow(clamp((1.0 - cos_theta), 0.0, 1.0), 5.0)));
}

float distribution_ggx(float n_dot_h, float roughness) {
    float a = (roughness * roughness);
    float a2 = (a * a);
    float denom_term = (((n_dot_h * n_dot_h) * (a2 - 1.0)) + 1.0);
    float denom = ((pi() * denom_term) * denom_term);
    return (a2 / denom);
}

float geometry_schlick_ggx(float n_dot_v, float roughness) {
    float r = (roughness + 1.0);
    float k = ((r * r) / 8.0);
    return (n_dot_v / ((n_dot_v * (1.0 - k)) + k));
}

float geometry_smith(float n_dot_v, float n_dot_l, float roughness) {
    return (geometry_schlick_ggx(n_dot_v, roughness) * geometry_schlick_ggx(n_dot_l, roughness));
}

float cook_torrance_specular(float n_dot_h, float n_dot_v, float n_dot_l, float h_dot_v, float roughness, float f0) {
    float d = distribution_ggx(n_dot_h, roughness);
    float f = fresnel_schlick(h_dot_v, f0);
    float g = geometry_smith(n_dot_v, n_dot_l, roughness);
    float numerator = ((d * f) * g);
    float denominator = (((4.0 * n_dot_v) * n_dot_l) + 0.0001);
    return (numerator / denominator);
}

float pbr_lighting(float n_dot_h, float n_dot_v, float n_dot_l, float h_dot_v, float albedo, float roughness, float metallic) {
    float f0 = ((0.04 * (1.0 - metallic)) + (albedo * metallic));
    float specular = cook_torrance_specular(n_dot_h, n_dot_v, n_dot_l, h_dot_v, roughness, f0);
    float ks = fresnel_schlick(h_dot_v, f0);
    float kd = ((1.0 - ks) * (1.0 - metallic));
    float diffuse = ((kd * albedo) / pi());
    return ((diffuse + specular) * n_dot_l);
}

float aces_tonemap(float x) {
    float num = (x * ((2.51 * x) + 0.03));
    float den = ((x * ((2.43 * x) + 0.59)) + 0.14);
    return clamp((num / den), 0.0, 1.0);
}

float linear_to_srgb(float x) {
    return clamp(pow(x, (1.0 / 2.2)), 0.0, 1.0);
}

float4 fs_pbr(float4 pos : SV_Position, float3 inputs) : SV_Target0 {
    float n_dot_l = clamp(inputs.x, 0.0, 1.0);
    float n_dot_h = clamp(inputs.y, 0.0, 1.0);
    float h_dot_v = clamp(inputs.z, 0.0, 1.0);
    float n_dot_v = 0.8;
    float albedo = 0.8;
    float roughness = 0.4;
    float metallic = 0.0;
    float lit = pbr_lighting(n_dot_h, n_dot_v, n_dot_l, h_dot_v, albedo, roughness, metallic);
    float mapped = aces_tonemap(lit);
    float final_val = linear_to_srgb(mapped);
    return float4(final_val, final_val, final_val, 1.0);
}

