// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double compute_diffuse(double normal_x, double normal_y, double normal_z, double light_x, double light_y, double light_z) {
    double _7;
    double _8;
    double _9;
    double _10;
    double _11;
    double d;
    _7 = (normal_x * light_x);
    _8 = (normal_y * light_y);
    _9 = (_7 + _8);
    _10 = (normal_z * light_z);
    _11 = (_9 + _10);
    d = _11;
    return d;
}

vec4 fs_main(vec3 color) {
    double _2;
    double diffuse;
    double _4;
    double _5;
    double r;
    double _7;
    double _8;
    double g;
    double _10;
    double _11;
    double b;
    vec4 _13;
    _2 = compute_diffuse(0.0, 1.0, 0.0, 0.577, 0.577, 0.577);
    diffuse = _2;
    _4 = color.x;
    _5 = (_4 * diffuse);
    r = _5;
    _7 = color.y;
    _8 = (_7 * diffuse);
    g = _8;
    _10 = color.z;
    _11 = (_10 * diffuse);
    b = _11;
    _13 = vec4(r, g, b, 1.0);
    return _13;
}

