// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float compute_diffuse(float normal_x, float normal_y, float normal_z, float light_x, float light_y, float light_z) {
    return (((normal_x * light_x) + (normal_y * light_y)) + (normal_z * light_z));
}

float4 fs_main(float4 pos : SV_Position, float3 color) : SV_Target0 {
    float diffuse = compute_diffuse(0.0, 1.0, 0.0, 0.577, 0.577, 0.577);
    float r = (color.x * diffuse);
    float g = (color.y * diffuse);
    float b = (color.z * diffuse);
    return float4(r, g, b, 1.0);
}

