// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float aces_tonemap(float x) {
    float a = 2.51;
    float b = 0.03;
    float c = 2.43;
    float d = 0.59;
    float e = 0.14;
    float num = (x * ((a * x) + b));
    float den = ((x * ((c * x) + d)) + e);
    return (num / den);
}

float srgb_to_linear(float c) {
    float _4;
    if (c <= 0.04045) {
        return (c / 12.92);
    } else {
        _4 = pow(((c + 0.055) / 1.055), 2.4);
    }
    return _4;
}

float linear_to_srgb(float c) {
    float _4;
    if (c <= 0.0031308) {
        return (c * 12.92);
    } else {
        _4 = ((1.055 * pow(c, 0.416667)) - 0.055);
    }
    return _4;
}

float process_color(float r, float g, float b, float exposure) {
    float linear_r = srgb_to_linear(r);
    float exposed = (linear_r * pow(2.0, exposure));
    float tonemapped = aces_tonemap(exposed);
    return linear_to_srgb(tonemapped);
}

