// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float fresnel_schlick(float cos_theta, float f0) {
    return (f0 + ((1.0 - f0) * pow((1.0 - cos_theta), 5.0)));
}

float fog_factor(float distance, float density) {
    float exponent = (distance * density);
    return clamp((1.0 - pow(2.718281828, (0.0 - (exponent * exponent)))), 0.0, 1.0);
}

float4 fs_main(float4 pos : SV_Position, float3 uv : TEXCOORD) : SV_Target0 {
    float x = uv.x;
    float y = uv.y;
    float s = sin((x * 3.14159));
    float c = cos((y * 3.14159));
    float r = sqrt(((x * x) + (y * y)));
    float f = floor((x * 10.0));
    float brightness = abs((s * c));
    float fresnel = fresnel_schlick(clamp(r, 0.0, 1.0), 0.04);
    float fog = fog_factor((r * 10.0), 0.1);
    return float4(brightness, fresnel, fog, 1.0);
}

