// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

uniform double ao_radius = 0.005;
uniform double ao_intensity = 2.0;
uniform double ao_bias = 0.001;
uniform double ao_samples = 16.0;

double hash(double n) {
    double _2;
    double _3;
    double x;
    double _5;
    _2 = sin(n);
    _3 = (_2 * 43758.5453);
    x = _3;
    _5 = fract(x);
    return _5;
}

double hash2(double a, double b) {
    double _3;
    double _4;
    double _5;
    double _6;
    _3 = (a * 127.1);
    _4 = (b * 311.7);
    _5 = (_3 + _4);
    _6 = hash(_5);
    return _6;
}

double compute_ao(double uv_x, double uv_y) {
    vec2 _3;
    double _4;
    double center_depth;
    bool _6;
    double _7;
    double occlusion;
    double i;
    bool _10;
    double _11;
    double _12;
    double _13;
    double _14;
    double _15;
    double angle;
    double _17;
    double _18;
    double _19;
    double _20;
    double dist;
    double _22;
    double _23;
    double _24;
    double sample_x;
    double _26;
    double _27;
    double _28;
    double sample_y;
    vec2 _30;
    double _31;
    double sample_depth;
    double _33;
    double diff;
    bool _35;
    double _36;
    int _37;
    double _38;
    double range;
    double _40;
    double _41;
    double _43;
    double _44;
    double _45;
    double _46;
    double ao;
    double _48;
    _3 = vec2(uv_x, uv_y);
    _4 = texture(depthbuffer, _3).r;
    center_depth = _4;
    _6 = (center_depth > 0.999);
    if (_6) {
        _7 = 1.0;
        return _7;
    } else {
        occlusion = 0.0;
        i = 0.0;
        _10 = (i < ao_samples);
        while (_10) {
            _11 = (uv_x * 100.0);
            _12 = (_11 + i);
            _13 = (uv_y * 100.0);
            _14 = hash2(_12, _13);
            _15 = (_14 * 6.2831853);
            angle = _15;
            _17 = (i * 7.3);
            _18 = (uv_x + uv_y);
            _19 = hash2(_17, _18);
            _20 = (_19 * ao_radius);
            dist = _20;
            _22 = cos(angle);
            _23 = (_22 * dist);
            _24 = (uv_x + _23);
            sample_x = _24;
            _26 = sin(angle);
            _27 = (_26 * dist);
            _28 = (uv_y + _27);
            sample_y = _28;
            _30 = vec2(sample_x, sample_y);
            _31 = texture(depthbuffer, _30).r;
            sample_depth = _31;
            _33 = (center_depth - sample_depth);
            diff = _33;
            _35 = (diff > ao_bias);
            if (_35) {
                _36 = abs(diff);
                _37 = (ao_radius / _36);
                _38 = smoothstep(0.0, 1.0, _37);
                range = _38;
                _40 = (occlusion + range);
                occlusion = _40;
                _41 = (i + 1.0);
                i = _41;
            } else {
                _43 = (i + 1.0);
                i = _43;
            }
        }
        _44 = (occlusion / ao_samples);
        _45 = (_44 * ao_intensity);
        _46 = (1.0 - _45);
        ao = _46;
        _48 = clamp(ao, 0.0, 1.0);
        _7 = _48;
    }
    return _7;
}

vec4 PS_SSAO(vec2 uv) {
    vec4 _2;
    vec4 color;
    double _4;
    double _5;
    double _6;
    double ao;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    vec4 _14;
    _2 = texture(backbuffer, uv);
    color = _2;
    _4 = uv.x;
    _5 = uv.y;
    _6 = compute_ao(_4, _5);
    ao = _6;
    _8 = color.x;
    _9 = (_8 * ao);
    _10 = color.y;
    _11 = (_10 * ao);
    _12 = color.z;
    _13 = (_12 * ao);
    _14 = vec4(_9, _11, _13, 1.0);
    return _14;
}

