// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double aces_tonemap(double x) {
    double a;
    double b;
    double c;
    double d;
    double e;
    double _7;
    double _8;
    double _9;
    double num;
    double _11;
    double _12;
    double _13;
    double _14;
    double den;
    double _16;
    a = 2.51;
    b = 0.03;
    c = 2.43;
    d = 0.59;
    e = 0.14;
    _7 = (a * x);
    _8 = (_7 + b);
    _9 = (x * _8);
    num = _9;
    _11 = (c * x);
    _12 = (_11 + d);
    _13 = (x * _12);
    _14 = (_13 + e);
    den = _14;
    _16 = (num / den);
    return _16;
}

