// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float aces_tonemap(float x) {
    float a = 2.51;
    float b = 0.03;
    float c = 2.43;
    float d = 0.59;
    float e = 0.14;
    float num = (x * ((a * x) + b));
    float den = ((x * ((c * x) + d)) + e);
    return (num / den);
}

