// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double fragment_main(double frag_x, double frag_y) {
    double r;
    double g;
    double _5;
    double b;
    double _7;
    double _8;
    r = frag_x;
    g = frag_y;
    _5 = (1.0 - frag_x);
    b = _5;
    _7 = (r + g);
    _8 = (_7 + b);
    return _8;
}

