// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float fragment_main(float4 pos : SV_Position, float frag_x, float frag_y) : SV_Target0 {
    float r = frag_x;
    float g = frag_y;
    float b = (1.0 - frag_x);
    return ((r + g) + b);
}

