// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float4 main(int vertex_id : SV_VertexID) : SV_Position {
    float _3;
    float _5;
    float _10;
    if (vertex_id == 0) {
        _3 = 0.0;
        float x = _3;
        if (vertex_id == 0) {
            _10 = (-0.5);
            float y = _10;
            return float4(x, y, 0.0, 1.0);
        } else {
            _10 = 0.5;
        }
    } else {
        if (vertex_id == 1) {
            _5 = 0.5;
            _3 = _5;
        } else {
            _5 = (-0.5);
        }
    }
    return float4(x, y, 0.0, 1.0);
}

