// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float vignette(float uv_x, float uv_y, float strength, float softness) {
    float dx = (uv_x - 0.5);
    float dy = (uv_y - 0.5);
    float dist = sqrt(((dx * dx) + (dy * dy)));
    float vig = smoothstep(0.5, (0.5 * softness), dist);
    return (1.0 - (strength * (1.0 - vig)));
}

float4 PS_Vignette(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float4 color = tex2D(ReShade::BackBuffer, uv);
    float vig = vignette(color.x, color.y, 0.5, 0.6);
    return float4((color.x * vig), (color.y * vig), (color.z * vig), 1.0);
}

