// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float pi() {
    return 3.14159265358979;
}

float beer_lambert(float density, float distance) {
    return pow(2.718281828, (0.0 - (density * distance)));
}

float henyey_greenstein(float cos_theta, float g) {
    float g2 = (g * g);
    float denom = ((1.0 + g2) - ((2.0 * g) * cos_theta));
    return ((1.0 - g2) / ((4.0 * pi()) * pow(denom, 1.5)));
}

float height_fog_density(float y, float base_density, float falloff) {
    return (base_density * pow(2.718281828, (0.0 - (falloff * clamp(y, 0.0, 100.0)))));
}

float raymarch_fog(float ray_start_y, float ray_end_y, float ray_length, float light_cos_angle, float base_density, float falloff, float scatter_g, int num_steps) {
    float total_transmittance;
    float in_scatter;
    int i;
    float step_size = (ray_length / 16.0);
    total_transmittance = 1.0;
    in_scatter = 0.0;
    i = 0;
    while (i < 16) {
        float t = (((float)(i) + 0.5) / 16.0);
        float sample_y = (ray_start_y + ((ray_end_y - ray_start_y) * t));
        float density = height_fog_density(sample_y, base_density, falloff);
        float step_extinction = beer_lambert(density, step_size);
        float phase = henyey_greenstein(light_cos_angle, scatter_g);
        in_scatter = (in_scatter + (((total_transmittance * density) * phase) * step_size));
        total_transmittance = (total_transmittance * step_extinction);
        i = (i + 1);
    }
    return in_scatter;
}

float aces(float x) {
    return clamp(((x * ((2.51 * x) + 0.03)) / ((x * ((2.43 * x) + 0.59)) + 0.14)), 0.0, 1.0);
}

float4 fs_fog(float4 pos : SV_Position, float3 ray_params) : SV_Target0 {
    float fog = raymarch_fog(ray_params.x, ray_params.y, 50.0, ray_params.z, 0.05, 0.1, 0.7, 16);
    float mapped = aces((fog * 5.0));
    return float4(mapped, mapped, mapped, 1.0);
}

