// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double pi() {
    return 3.14159265358979;
}

double beer_lambert(double density, double distance) {
    double _3;
    double _4;
    double _5;
    _3 = (density * distance);
    _4 = (0.0 - _3);
    _5 = pow(2.718281828, _4);
    return _5;
}

double henyey_greenstein(double cos_theta, double g) {
    double _3;
    double g2;
    double _5;
    double _6;
    double _7;
    double _8;
    double denom;
    double _10;
    double _11;
    double _12;
    double _13;
    double _14;
    double _15;
    _3 = (g * g);
    g2 = _3;
    _5 = (1.0 + g2);
    _6 = (2.0 * g);
    _7 = (_6 * cos_theta);
    _8 = (_5 - _7);
    denom = _8;
    _10 = (1.0 - g2);
    _11 = pi();
    _12 = (4.0 * _11);
    _13 = pow(denom, 1.5);
    _14 = (_12 * _13);
    _15 = (_10 / _14);
    return _15;
}

double height_fog_density(double y, double base_density, double falloff) {
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    _4 = clamp(y, 0.0, 100.0);
    _5 = (falloff * _4);
    _6 = (0.0 - _5);
    _7 = pow(2.718281828, _6);
    _8 = (base_density * _7);
    return _8;
}

double raymarch_fog(double ray_start_y, double ray_end_y, double ray_length, double light_cos_angle, double base_density, double falloff, double scatter_g, int num_steps) {
    double _9;
    double step_size;
    double total_transmittance;
    double in_scatter;
    int i;
    bool _14;
    double _15;
    double _16;
    double _17;
    double t;
    double _19;
    double _20;
    double _21;
    double sample_y;
    double _23;
    double density;
    double _25;
    double step_extinction;
    double _27;
    double phase;
    double _29;
    double _30;
    double _31;
    double _32;
    double _33;
    int _34;
    _9 = (ray_length / 16.0);
    step_size = _9;
    total_transmittance = 1.0;
    in_scatter = 0.0;
    i = 0;
    _14 = (i < 16);
    while (_14) {
        _15 = double(i);
        _16 = (_15 + 0.5);
        _17 = (_16 / 16.0);
        t = _17;
        _19 = (ray_end_y - ray_start_y);
        _20 = (_19 * t);
        _21 = (ray_start_y + _20);
        sample_y = _21;
        _23 = height_fog_density(sample_y, base_density, falloff);
        density = _23;
        _25 = beer_lambert(density, step_size);
        step_extinction = _25;
        _27 = henyey_greenstein(light_cos_angle, scatter_g);
        phase = _27;
        _29 = (total_transmittance * density);
        _30 = (_29 * phase);
        _31 = (_30 * step_size);
        _32 = (in_scatter + _31);
        in_scatter = _32;
        _33 = (total_transmittance * step_extinction);
        total_transmittance = _33;
        _34 = (i + 1);
        i = _34;
    }
    return in_scatter;
}

double aces(double x) {
    double _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    double _8;
    double _9;
    double _10;
    _2 = (2.51 * x);
    _3 = (_2 + 0.03);
    _4 = (x * _3);
    _5 = (2.43 * x);
    _6 = (_5 + 0.59);
    _7 = (x * _6);
    _8 = (_7 + 0.14);
    _9 = (_4 / _8);
    _10 = clamp(_9, 0.0, 1.0);
    return _10;
}

vec4 fs_fog(vec3 ray_params) {
    double _2;
    double _3;
    double _4;
    double _5;
    double fog;
    double _7;
    double _8;
    double mapped;
    vec4 _10;
    _2 = ray_params.x;
    _3 = ray_params.y;
    _4 = ray_params.z;
    _5 = raymarch_fog(_2, _3, 50.0, _4, 0.05, 0.1, 0.7, 16);
    fog = _5;
    _7 = (fog * 5.0);
    _8 = aces(_7);
    mapped = _8;
    _10 = vec4(mapped, mapped, mapped, 1.0);
    return _10;
}

