// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

uniform float ao_radius = 0.01;
uniform float ao_intensity = 1.5;

float hash(float n) {
    float x = (sin(n) * 43758.5453);
    return frac(x);
}

float hash2(float a, float b) {
    return hash(((a * 127.1) + (b * 311.7)));
}

float sample_offset_x(float i, float uv_x, float uv_y) {
    float angle = (hash2((i * 3.17), (uv_x + uv_y)) * 6.2831853);
    float dist = (hash2(((uv_x * 50.0) + i), (uv_y * 50.0)) * ao_radius);
    return (cos(angle) * dist);
}

float sample_offset_y(float i, float uv_x, float uv_y) {
    float angle = (hash2((i * 3.17), (uv_x + uv_y)) * 6.2831853);
    float dist = (hash2(((uv_x * 50.0) + i), (uv_y * 50.0)) * ao_radius);
    return (sin(angle) * dist);
}

float compare_depth(float center_d, float sample_x, float sample_y) {
    float _14;
    float sample_d = ReShade::GetLinearizedDepth(float2(sample_x, sample_y));
    float diff = (center_d - sample_d);
    if (diff > 0.0005) {
        float range = smoothstep(0.0, 1.0, (ao_radius / abs(diff)));
        return range;
    } else {
        _14 = 0.0;
    }
    return _14;
}

float compute_ssao(float uv_x, float uv_y) {
    float _7;
    float occlusion;
    float i;
    float center_d = ReShade::GetLinearizedDepth(float2(uv_x, uv_y));
    if (center_d > 0.999) {
        return 1.0;
    } else {
        occlusion = 0.0;
        i = 0.0;
        while (i < 8.0) {
            float ox = sample_offset_x(i, uv_x, uv_y);
            float oy = sample_offset_y(i, uv_x, uv_y);
            occlusion = (occlusion + compare_depth(center_d, (uv_x + ox), (uv_y + oy)));
            i = (i + 1.0);
        }
        float ao = (1.0 - ((occlusion / 8.0) * ao_intensity));
        _7 = clamp(ao, 0.0, 1.0);
    }
    return _7;
}

float4 PS_AmbientOcclusion(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float4 color = tex2D(ReShade::BackBuffer, uv);
    float ao = compute_ssao(uv.x, uv.y);
    return float4((color.x * ao), (color.y * ao), (color.z * ao), 1.0);
}

