// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

uniform float threshold = 0.7;
uniform float intensity = 1.0;

float luminance(float r, float g, float b) {
    return (((r * 0.2126) + (g * 0.7152)) + (b * 0.0722));
}

float extract_bright_r(float r, float g, float b) {
    float lum = luminance(r, g, b);
    float brightness = smoothstep(threshold, (threshold + 0.1), lum);
    return (r * brightness);
}

float extract_bright_g(float r, float g, float b) {
    float lum = luminance(r, g, b);
    float brightness = smoothstep(threshold, (threshold + 0.1), lum);
    return (g * brightness);
}

float extract_bright_b(float r, float g, float b) {
    float lum = luminance(r, g, b);
    float brightness = smoothstep(threshold, (threshold + 0.1), lum);
    return (b * brightness);
}

float gaussian_weight(float offset) {
    float sigma = 2.0;
    float x = (offset / sigma);
    return exp(((x * x) * (-0.5)));
}

float blur_channel_x(float uv_x, float uv_y, float texel) {
    float w0 = gaussian_weight(0.0);
    float w1 = gaussian_weight(1.0);
    float w2 = gaussian_weight(2.0);
    float w3 = gaussian_weight(3.0);
    float w4 = gaussian_weight(4.0);
    float4 c0 = tex2D(ReShade::BackBuffer, float2(uv_x, uv_y));
    float4 c1p = tex2D(ReShade::BackBuffer, float2((uv_x + texel), uv_y));
    float4 c1n = tex2D(ReShade::BackBuffer, float2((uv_x - texel), uv_y));
    float4 c2p = tex2D(ReShade::BackBuffer, float2((uv_x + (texel * 2.0)), uv_y));
    float4 c2n = tex2D(ReShade::BackBuffer, float2((uv_x - (texel * 2.0)), uv_y));
    float4 c3p = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y + texel)));
    float4 c3n = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y - texel)));
    float4 c4p = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y + (texel * 2.0))));
    float4 c4n = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y - (texel * 2.0))));
    float total = (((((((((c0.x * w0) + (c1p.x * w1)) + (c1n.x * w1)) + (c2p.x * w2)) + (c2n.x * w2)) + (c3p.x * w3)) + (c3n.x * w3)) + (c4p.x * w4)) + (c4n.x * w4));
    float weight_sum = ((((w0 + (w1 * 2.0)) + (w2 * 2.0)) + (w3 * 2.0)) + (w4 * 2.0));
    return (total / weight_sum);
}

float blur_channel_y(float uv_x, float uv_y, float texel) {
    float w0 = gaussian_weight(0.0);
    float w1 = gaussian_weight(1.0);
    float w2 = gaussian_weight(2.0);
    float w3 = gaussian_weight(3.0);
    float w4 = gaussian_weight(4.0);
    float4 c0 = tex2D(ReShade::BackBuffer, float2(uv_x, uv_y));
    float4 c1p = tex2D(ReShade::BackBuffer, float2((uv_x + texel), uv_y));
    float4 c1n = tex2D(ReShade::BackBuffer, float2((uv_x - texel), uv_y));
    float4 c2p = tex2D(ReShade::BackBuffer, float2((uv_x + (texel * 2.0)), uv_y));
    float4 c2n = tex2D(ReShade::BackBuffer, float2((uv_x - (texel * 2.0)), uv_y));
    float4 c3p = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y + texel)));
    float4 c3n = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y - texel)));
    float4 c4p = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y + (texel * 2.0))));
    float4 c4n = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y - (texel * 2.0))));
    float total = (((((((((c0.y * w0) + (c1p.y * w1)) + (c1n.y * w1)) + (c2p.y * w2)) + (c2n.y * w2)) + (c3p.y * w3)) + (c3n.y * w3)) + (c4p.y * w4)) + (c4n.y * w4));
    float weight_sum = ((((w0 + (w1 * 2.0)) + (w2 * 2.0)) + (w3 * 2.0)) + (w4 * 2.0));
    return (total / weight_sum);
}

float blur_channel_z(float uv_x, float uv_y, float texel) {
    float w0 = gaussian_weight(0.0);
    float w1 = gaussian_weight(1.0);
    float w2 = gaussian_weight(2.0);
    float w3 = gaussian_weight(3.0);
    float w4 = gaussian_weight(4.0);
    float4 c0 = tex2D(ReShade::BackBuffer, float2(uv_x, uv_y));
    float4 c1p = tex2D(ReShade::BackBuffer, float2((uv_x + texel), uv_y));
    float4 c1n = tex2D(ReShade::BackBuffer, float2((uv_x - texel), uv_y));
    float4 c2p = tex2D(ReShade::BackBuffer, float2((uv_x + (texel * 2.0)), uv_y));
    float4 c2n = tex2D(ReShade::BackBuffer, float2((uv_x - (texel * 2.0)), uv_y));
    float4 c3p = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y + texel)));
    float4 c3n = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y - texel)));
    float4 c4p = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y + (texel * 2.0))));
    float4 c4n = tex2D(ReShade::BackBuffer, float2(uv_x, (uv_y - (texel * 2.0))));
    float total = (((((((((c0.z * w0) + (c1p.z * w1)) + (c1n.z * w1)) + (c2p.z * w2)) + (c2n.z * w2)) + (c3p.z * w3)) + (c3n.z * w3)) + (c4p.z * w4)) + (c4n.z * w4));
    float weight_sum = ((((w0 + (w1 * 2.0)) + (w2 * 2.0)) + (w3 * 2.0)) + (w4 * 2.0));
    return (total / weight_sum);
}

float4 PS_Bloom(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float4 color = tex2D(ReShade::BackBuffer, uv);
    float br = extract_bright_r(color.x, color.y, color.z);
    float bg = extract_bright_g(color.x, color.y, color.z);
    float bb = extract_bright_b(color.x, color.y, color.z);
    float blur_r = blur_channel_x(uv.x, uv.y, 0.002);
    float blur_g = blur_channel_y(uv.x, uv.y, 0.002);
    float blur_b = blur_channel_z(uv.x, uv.y, 0.002);
    float r = (color.x + (blur_r * intensity));
    float g = (color.y + (blur_g * intensity));
    float b = (color.z + (blur_b * intensity));
    return float4(clamp(r, 0.0, 1.0), clamp(g, 0.0, 1.0), clamp(b, 0.0, 1.0), 1.0);
}

