// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

uniform float strength = 0.005;

float offset_uv_x(float uv_x, float uv_y, float direction) {
    float _19;
    float dx = (uv_x - 0.5);
    float dy = (uv_y - 0.5);
    float dist = sqrt(((dx * dx) + (dy * dy)));
    if (dist > 0.001) {
        return (uv_x + ((((dx / dist) * dist) * strength) * direction));
    } else {
        _19 = uv_x;
    }
    return _19;
}

float offset_uv_y(float uv_x, float uv_y, float direction) {
    float _19;
    float dx = (uv_x - 0.5);
    float dy = (uv_y - 0.5);
    float dist = sqrt(((dx * dx) + (dy * dy)));
    if (dist > 0.001) {
        return (uv_y + ((((dy / dist) * dist) * strength) * direction));
    } else {
        _19 = uv_y;
    }
    return _19;
}

float4 PS_ChromaticAberration(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float red_x = offset_uv_x(uv.x, uv.y, 1.0);
    float red_y = offset_uv_y(uv.x, uv.y, 1.0);
    float4 red_sample = tex2D(ReShade::BackBuffer, float2(red_x, red_y));
    float4 green_sample = tex2D(ReShade::BackBuffer, uv);
    float blue_x = offset_uv_x(uv.x, uv.y, (-1.0));
    float blue_y = offset_uv_y(uv.x, uv.y, (-1.0));
    float4 blue_sample = tex2D(ReShade::BackBuffer, float2(blue_x, blue_y));
    return float4(red_sample.x, green_sample.y, blue_sample.z, 1.0);
}

