// Dump the built-in triangle shaders as C arrays
// Run: cargo run --bin dump_shaders > triangle_shaders.h

use quantalang::codegen::backend::spirv::SpirVBackend;

fn main() {
    let mut backend = SpirVBackend::new();

    let vert = backend.generate_triangle_vertex_shader();
    let frag = backend.generate_triangle_fragment_shader();

    println!("// Auto-generated by QuantaLang compiler");
    println!("// Vertex shader: {} bytes", vert.len());
    print!("static const unsigned char VERT_SPV[] = {{");
    for (i, b) in vert.iter().enumerate() {
        if i % 16 == 0 { print!("\n    "); }
        print!("0x{:02x},", b);
    }
    println!("\n}};");
    println!("static const size_t VERT_SPV_SIZE = {};", vert.len());

    println!("// Fragment shader: {} bytes", frag.len());
    print!("static const unsigned char FRAG_SPV[] = {{");
    for (i, b) in frag.iter().enumerate() {
        if i % 16 == 0 { print!("\n    "); }
        print!("0x{:02x},", b);
    }
    println!("\n}};");
    println!("static const size_t FRAG_SPV_SIZE = {};", frag.len());
}
