// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

uniform float grain_amount = 0.08;
uniform float grain_size = 1.0;
uniform float frame_time = 0.0;

float hash(float n) {
    float x = (sin(n) * 43758.5453);
    return frac(x);
}

float hash2d(float x, float y) {
    return hash((((x * 12.9898) + (y * 78.233)) + (frame_time * 5.7831)));
}

float grain_noise(float uv_x, float uv_y) {
    float scale = (512.0 / grain_size);
    float qx = (floor((uv_x * scale)) / scale);
    float qy = (floor((uv_y * scale)) / scale);
    float noise = hash2d(qx, qy);
    return ((noise - 0.5) * 2.0);
}

float apply_grain(float color, float noise) {
    float grained = (color + ((noise * grain_amount) * (1.0 - (color * 0.5))));
    return clamp(grained, 0.0, 1.0);
}

float4 PS_FilmGrain(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target0 {
    float4 color = tex2D(ReShade::BackBuffer, uv);
    float noise = grain_noise(uv.x, uv.y);
    float r = apply_grain(color.x, noise);
    float g = apply_grain(color.y, noise);
    float b = apply_grain(color.z, noise);
    return float4(r, g, b, 1.0);
}

