// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double aces_tonemap(double x) {
    double a;
    double b;
    double c;
    double d;
    double e;
    double _7;
    double _8;
    double _9;
    double num;
    double _11;
    double _12;
    double _13;
    double _14;
    double den;
    double _16;
    a = 2.51;
    b = 0.03;
    c = 2.43;
    d = 0.59;
    e = 0.14;
    _7 = (a * x);
    _8 = (_7 + b);
    _9 = (x * _8);
    num = _9;
    _11 = (c * x);
    _12 = (_11 + d);
    _13 = (x * _12);
    _14 = (_13 + e);
    den = _14;
    _16 = (num / den);
    return _16;
}

double srgb_to_linear(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = (c <= 0.04045);
    if (_2) {
        _3 = (c / 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = (c + 0.055);
        _6 = (_5 / 1.055);
        _7 = pow(_6, 2.4);
        _4 = _7;
    }
    return _4;
}

double linear_to_srgb(double c) {
    bool _2;
    double _3;
    double _4;
    double _5;
    double _6;
    double _7;
    _2 = (c <= 0.0031308);
    if (_2) {
        _3 = (c * 12.92);
        _4 = _3;
        return _4;
    } else {
        _5 = pow(c, 0.416667);
        _6 = (1.055 * _5);
        _7 = (_6 - 0.055);
        _4 = _7;
    }
    return _4;
}

double process_color(double r, double g, double b, double exposure) {
    double _5;
    double linear_r;
    double _7;
    double _8;
    double exposed;
    double _10;
    double tonemapped;
    double _12;
    _5 = srgb_to_linear(r);
    linear_r = _5;
    _7 = pow(2.0, exposure);
    _8 = (linear_r * _7);
    exposed = _8;
    _10 = aces_tonemap(exposed);
    tonemapped = _10;
    _12 = linear_to_srgb(tonemapped);
    return _12;
}

