// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

struct quanta_vec2 {
    float x;
    float y;
};

struct quanta_vec3 {
    float x;
    float y;
    float z;
};

struct quanta_vec4 {
    float x;
    float y;
    float z;
    float w;
};

float aces_tonemap(float x) {
    float _ret;
    float a;
    float b;
    float c;
    float d;
    float e;
    float _7;
    float _8;
    float _9;
    float num;
    float _11;
    float _12;
    float _13;
    float _14;
    float den;
    float _16;
    // bb0:
    a = 2.51;
    b = 0.03;
    c = 2.43;
    d = 0.59;
    e = 0.14;
    _7 = (a * x);
    _8 = (_7 + b);
    _9 = (x * _8);
    num = _9;
    _11 = (c * x);
    _12 = (_11 + d);
    _13 = (x * _12);
    _14 = (_13 + e);
    den = _14;
    _16 = (num / den);
    return _16;
}

int main() {
    int _ret;
    float _1;
    float r;
    float _3;
    float g;
    float _5;
    float b;
    int _7;
    // bb0:
    // bb1:
    r = _1;
    // bb2:
    g = _3;
    // bb3:
    b = _5;
    _7 = 0;
    // bb4:
    return 0;
}

