// Generated by QuantaLang Compiler
// Target: HLSL (DirectX / ReShade)
// Do not edit manually

float4 main(int vertex_id : SV_VertexID) : SV_Position {
    bool _2;
    float _3;
    bool _4;
    float _5;
    float _6;
    float x;
    bool _8;
    float _9;
    float _10;
    float y;
    float4 _12;
    _2 = (vertex_id == 0);
    if (_2) {
        _3 = 0.0;
        x = _3;
        _8 = (vertex_id == 0);
        if (_8) {
            _9 = (-0.5);
            _10 = _9;
            y = _10;
            _12 = float4(x, y, 0.0, 1.0);
            return _12;
        } else {
            _10 = 0.5;
        }
    } else {
        _4 = (vertex_id == 1);
        if (_4) {
            _5 = 0.5;
            _3 = _5;
        } else {
            _6 = (-0.5);
            _5 = _6;
        }
    }
    return _12;
}

