// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double vignette(double uv_x, double uv_y, double strength, double softness) {
    double _5;
    double dx;
    double _7;
    double dy;
    double _9;
    double _10;
    double _11;
    double _12;
    double dist;
    double _14;
    double _15;
    double vig;
    double _17;
    double _18;
    double _19;
    _5 = (uv_x - 0.5);
    dx = _5;
    _7 = (uv_y - 0.5);
    dy = _7;
    _9 = (dx * dx);
    _10 = (dy * dy);
    _11 = (_9 + _10);
    _12 = sqrt(_11);
    dist = _12;
    _14 = (0.5 * softness);
    _15 = smoothstep(0.5, _14, dist);
    vig = _15;
    _17 = (1.0 - vig);
    _18 = (strength * _17);
    _19 = (1.0 - _18);
    return _19;
}

vec4 PS_Vignette(vec2 uv) {
    vec4 _2;
    vec4 color;
    double _4;
    double _5;
    double _6;
    double vig;
    double _8;
    double _9;
    double _10;
    double _11;
    double _12;
    double _13;
    vec4 _14;
    _2 = texture(backbuffer, uv);
    color = _2;
    _4 = color.x;
    _5 = color.y;
    _6 = vignette(_4, _5, 0.5, 0.6);
    vig = _6;
    _8 = color.x;
    _9 = (_8 * vig);
    _10 = color.y;
    _11 = (_10 * vig);
    _12 = color.z;
    _13 = (_12 * vig);
    _14 = vec4(_9, _11, _13, 1.0);
    return _14;
}

