// Generated by QuantaLang Compiler
// Target: GLSL (OpenGL / Vulkan)
// Do not edit manually

#version 450

double vignette(double uv_x, double uv_y, double strength, double softness) {
    double dx = (uv_x - 0.5);
    double dy = (uv_y - 0.5);
    double dist = sqrt(((dx * dx) + (dy * dy)));
    double vig = smoothstep(0.5, (0.5 * softness), dist);
    return (1.0 - (strength * (1.0 - vig)));
}

vec4 PS_Vignette(vec2 uv) {
    vec4 color = texture(backbuffer, uv);
    double vig = vignette(color.x, color.y, 0.5, 0.6);
    return vec4((color.x * vig), (color.y * vig), (color.z * vig), 1.0);
}

